/* =========================================================
   ORBIT BIZASSIST — UI CORE
   Premium application shell, navigation and account surface
   ========================================================= */

(() => {
  "use strict";
  const APP = "#app";
  const NAV_ITEMS = [
    { id: "dashboard", label: "Overview", icon: "⌂", hint: "Home" },
    { id: "invoices", label: "Invoices", icon: "▣", hint: "Billing" },
    { id: "khata", label: "Khata", icon: "₹", hint: "Receivables" },
    { id: "inventory", label: "Inventory", icon: "▤", hint: "Stock" },
    { id: "expenses", label: "Expenses", icon: "↗", hint: "Spending" },
    { id: "reports", label: "Reports", icon: "◴", hint: "Insights" }
  ];
  const MORE_ITEMS = [
    { id: "staff", label: "Staff", icon: "♙", hint: "Team" },
    { id: "settings", label: "Settings", icon: "⚙", hint: "Workspace" }
  ];
  function activeRoute(){return window.AppRouter?.current?.()||"dashboard";}
  function getState(){return window.AppState?.get?.()||{};}
  function getUser(){return getState().user||null;}
  function getBusiness(){const s=getState();return s.businesses?.find(b=>b.id===s.activeBusiness)||s.businesses?.[0]||null;}
  function userName(){const u=getUser();return u?.name||u?.user_metadata?.full_name||u?.email?.split("@")[0]||"Owner";}
  function userAvatar(){return getUser()?.avatar||"";}
  function initials(name){return String(name||"Owner").trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||"").join("")||"O";}
  function escapeHTML(v){if(window.AppUtils?.esc)return window.AppUtils.esc(v);return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
  function avatarHTML(size="sm"){const n=userName(),a=userAvatar();return a?`<img class="app-avatar ${size}" src="${escapeHTML(a)}" alt="${escapeHTML(n)}">`:`<span class="app-avatar ${size}" aria-hidden="true">${escapeHTML(initials(n))}</span>`;}
  function navigationItem(item,current){const active=item.id===current;return `<button class="nav-item ${active?"active":""}" type="button" data-route="${item.id}" aria-current="${active?"page":"false"}" title="${escapeHTML(item.label)} — ${escapeHTML(item.hint)}"><span class="nav-icon" aria-hidden="true">${item.icon}</span><span class="nav-copy"><strong>${escapeHTML(item.label)}</strong><small>${escapeHTML(item.hint)}</small></span>${active?`<i class="nav-active-dot" aria-hidden="true"></i>`:""}</button>`;}
  function sidebar(){const current=activeRoute(),b=getBusiness(),n=userName();return `<aside class="sidebar" aria-label="Orbit BizAssist navigation"><div class="sidebar-brand-row"><div class="sidebar-brand"><span class="brand-mark" aria-hidden="true">O</span><span><strong>Orbit</strong><small>BizAssist</small></span></div><button class="sidebar-collapse" type="button" aria-label="Collapse navigation" title="Collapse navigation" data-action="sidebar-collapse">‹</button></div><button class="business-switch" type="button" data-action="business-switch" aria-label="Current business: ${escapeHTML(b?.name||"My Business")}"><span class="business-logo" aria-hidden="true">${escapeHTML(initials(b?.name||"MB").charAt(0))}</span><span class="business-copy"><small>WORKSPACE</small><strong>${escapeHTML(b?.name||"My Business")}</strong></span><span class="business-chevron" aria-hidden="true">⌄</span></button><button class="global-search" type="button" data-action="global-search" aria-label="Search Orbit BizAssist" title="Search (Ctrl/Cmd + K)"><span aria-hidden="true">⌕</span><span>Search anything…</span><kbd>⌘K</kbd></button><div class="nav-section-label">Workspace</div><nav class="sidebar-nav" aria-label="Main navigation">${NAV_ITEMS.map(x=>navigationItem(x,current)).join("")}</nav><div class="nav-divider"></div><div class="nav-section-label">Manage</div><nav class="sidebar-nav" aria-label="Management navigation">${MORE_ITEMS.map(x=>navigationItem(x,current)).join("")}</nav><div class="sidebar-bottom"><div class="sidebar-status"><span class="status-dot" aria-hidden="true"></span><span><strong>Cloud synced</strong><small>Your data is up to date</small></span></div><button class="sidebar-profile" type="button" data-action="profile" aria-label="Open profile for ${escapeHTML(n)}">${avatarHTML("sm")}<span><strong>${escapeHTML(n)}</strong><small>${escapeHTML(getUser()?.role||"Owner / Admin")}</small></span><span class="profile-more" aria-hidden="true">•••</span></button></div></aside>`;}
  function pageTitle(route){const item=[...NAV_ITEMS,...MORE_ITEMS].find(x=>x.id===route);return item?.label||"Overview";}
  function topbar(){const r=activeRoute(),b=getBusiness();return `<header class="topbar"><div class="topbar-heading"><span class="breadcrumb">${escapeHTML(b?.name||"Workspace")} <b>›</b> ${escapeHTML(pageTitle(r))}</span><h1>${escapeHTML(pageTitle(r))}</h1></div><div class="topbar-actions"><button class="topbar-search" type="button" data-action="global-search" aria-label="Search" title="Search (Ctrl/Cmd + K)"><span aria-hidden="true">⌕</span><span>Search</span><kbd>⌘K</kbd></button><button class="icon-btn mobile-menu-button" type="button" data-action="mobile-menu" aria-label="Open navigation" title="Menu">☰</button><button class="icon-btn notification-button" type="button" data-action="notifications" aria-label="Notifications" title="Notifications"><span aria-hidden="true">♢</span><i aria-hidden="true"></i></button><button class="topbar-avatar" type="button" data-action="profile" aria-label="Open your profile" title="Profile">${avatarHTML("sm")}</button></div></header>`;}
  function routeView(){const r=activeRoute();if(r==="dashboard"&&typeof window.dashboard==="function")return window.dashboard();if(r==="invoices"&&typeof window.POS?.view==="function"){const h=window.POS.view();setTimeout(()=>window.POS.render(),0);return h;}if(r==="inventory"&&typeof window.Inventory?.view==="function"){const h=window.Inventory.view();setTimeout(()=>window.Inventory.render(),0);return h;}if(r==="khata"&&typeof window.Khata?.view==="function"){const h=window.Khata.view();setTimeout(()=>window.Khata.render(),0);return h;}if(["expenses","reports","staff","settings"].includes(r)&&window.BusinessTools){const h=window.BusinessTools[r]();setTimeout(()=>window.BusinessTools.render(),0);return h;}return `<main class="page"><section class="empty-state"><div class="empty-icon" aria-hidden="true">✦</div><span class="eyebrow">Coming next</span><h4>${escapeHTML(pageTitle(r))}</h4><p>This workspace is being built module by module. Your business data and authentication remain connected.</p><button class="primary-btn" type="button" data-route="dashboard">Back to Overview</button></section></main>`;}
  function appShell(){return `<div class="app-shell">${sidebar()}<div class="main-content">${topbar()}${routeView()}</div></div>`;}
  function render(){const root=document.querySelector(APP);if(!root){console.error("Orbit BizAssist: #app element not found.");return;}const u=getUser();if(!u){root.innerHTML=typeof window.auth==="function"?window.auth():`<section class="auth-page"><div class="auth-panel"><div class="login-box"><h2>Orbit BizAssist</h2><p>Authentication interface unavailable.</p></div></div></section>`;root.setAttribute("aria-busy","false");return;}if(!getState().onboarding?.completed){root.innerHTML=typeof window.AppOnboarding?.view==="function"?window.AppOnboarding.view():`<section class="auth-card"><h2>Setting up your workspace…</h2></section>`;root.setAttribute("aria-busy","false");setTimeout(()=>window.AppOnboarding?.bind?.(),0);return;}root.innerHTML=appShell();root.setAttribute("aria-busy","false");}
  function toggleMobileNavigation(){document.body.classList.toggle("mobile-nav-open");}
  function closeMobileNavigation(){document.body.classList.remove("mobile-nav-open");}
  function openGlobalSearch(){const existing=document.querySelector("[data-command-palette]");if(existing){existing.querySelector("input")?.focus();return;}document.body.insertAdjacentHTML("beforeend",`<div class="command-overlay" data-command-palette role="dialog" aria-modal="true" aria-label="Search Orbit BizAssist"><div class="command-palette"><div class="command-head"><span class="command-icon">⌕</span><input type="search" autocomplete="off" placeholder="Search pages, customers, products…" aria-label="Search Orbit BizAssist"><button type="button" data-action="close-command" aria-label="Close search">×</button></div><div class="command-results">${[...NAV_ITEMS,...MORE_ITEMS].map(x=>`<button type="button" data-route="${x.id}"><span>${x.icon}</span><strong>${escapeHTML(x.label)}</strong><small>${escapeHTML(x.hint)}</small></button>`).join("")}</div><div class="command-foot"><span>Navigate</span><kbd>↑</kbd><kbd>↓</kbd><span>Select</span><kbd>↵</kbd><span>Close</span><kbd>Esc</kbd></div></div></div>`);document.querySelector("[data-command-palette] input")?.focus();}
  function closeGlobalSearch(){document.querySelector("[data-command-palette]")?.remove();}
  function signOut(){try{window.orbitCloud?.signOut?.();}catch(e){console.error("Orbit BizAssist sign-out error:",e);}if(window.AppState?.merge)window.AppState.merge({user:null,page:"dashboard"});closeMobileNavigation();closeGlobalSearch();if(window.location.hash)window.history.replaceState(null,"",window.location.pathname+window.location.search);render();}
  function handleClick(event){const rt=event.target.closest("[data-route]");if(rt){event.preventDefault();closeGlobalSearch();closeMobileNavigation();window.AppRouter?.go?.(rt.dataset.route);return;}const a=event.target.closest("[data-action]");if(!a)return;const action=a.dataset.action;if(action==="signout"){signOut();return;}if(action==="profile"){window.AppProfile?.open?.();return;}if(action==="global-search"){openGlobalSearch();return;}if(action==="close-command"){closeGlobalSearch();return;}if(action==="notifications"){if(typeof toast==="function")toast("You’re all caught up.");return;}if(action==="mobile-menu"){toggleMobileNavigation();return;}if(action==="sidebar-collapse"){document.body.classList.toggle("sidebar-collapsed");return;}if(action==="business-switch"){if(typeof toast==="function")toast("Business switching will be available in Workspace settings.");return;}}
  document.addEventListener("click",handleClick);document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openGlobalSearch();return;}if(e.key==="Escape"){closeGlobalSearch();closeMobileNavigation();}});window.addEventListener("hashchange",()=>{closeMobileNavigation();closeGlobalSearch();render();});
  window.AppUI=Object.freeze({render,appShell,sidebar,topbar,routeView,closeMobileNavigation,signOut});window.render=render;
})();