/* =========================================================
   ORBIT BIZASSIST — CUSTOMERS
   Customer directory, balances and invoice history
   ========================================================= */
(() => {
  "use strict";
  const esc=v=>window.AppUtils?.esc?window.AppUtils.esc(v):String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const money=v=>window.AppUtils?.money?window.AppUtils.money(v):new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v)||0);
  const business=()=>window.AppState?.business?.()||null;
  const customers=()=>{const b=business(),contacts=Array.isArray(b?.contacts)?b.contacts:[],map=new Map();contacts.forEach(c=>c?.id&&map.set(c.id,{...c}));(b?.invoices||[]).forEach(i=>{const n=i?.customerName||i?.customer?.name||i?.customer||"Walk-in customer";if(n==="Walk-in customer")return;const id=i.customerId||`customer-${String(n).toLowerCase().replace(/\W+/g,"-")}`;if(!map.has(id))map.set(id,{id,name:n,phone:i.customerPhone||i.customer?.phone||"",email:i.customerEmail||i.customer?.email||""});});return [...map.values()];};
  const stats=c=>{const inv=(business()?.invoices||[]).filter(i=>String(i.customerId||i.customerName||i.customer||"").toLowerCase()===String(c.id||c.name).toLowerCase()||String(i.customerName||i.customer||"").toLowerCase()===String(c.name).toLowerCase());const total=inv.reduce((s,i)=>s+Number(i.total??i.grandTotal??i.amount??0),0),paid=inv.reduce((s,i)=>s+Number(i.paidAmount??i.paid??(String(i.status||"").toLowerCase()==="paid"?(i.total??i.grandTotal??0):0)),0);return{count:inv.length,total,paid,outstanding:Math.max(0,total-paid)};};
  function view(){return `<main class="page customers-page"><section class="page-hero"><div><span class="eyebrow">Relationships</span><h2>Customers</h2><p>Customer details, purchase history and outstanding balances in one place.</p></div><button class="primary-btn" type="button" data-customer-action="add">+ Add customer</button></section><section class="customer-toolbar"><input id="customer-search" type="search" placeholder="Search name, phone or email…" autocomplete="off"><span class="customer-count" id="customer-count"></span></section><section id="customer-list" class="customer-grid"></section><div id="customer-modal-root"></div></main>`;}
  function render(){const root=document.getElementById("customer-list");if(!root)return;const q=(document.getElementById("customer-search")?.value||"").trim().toLowerCase(),list=customers().filter(c=>!q||[c.name,c.phone,c.email].some(v=>String(v||"").toLowerCase().includes(q))),count=document.getElementById("customer-count");if(count)count.textContent=`${list.length} customer${list.length===1?"":"s"}`;root.innerHTML=list.length?list.map(c=>{const s=stats(c);return `<article class="customer-card"><div class="customer-card-head"><div class="customer-avatar">${esc(String(c.name||"C").trim().charAt(0).toUpperCase())}</div><div><h3>${esc(c.name||"Unnamed customer")}</h3><p>${esc(c.phone||c.email||"No contact details")}</p></div></div><div class="customer-stats"><span><small>Invoices</small><b>${s.count}</b></span><span><small>Purchased</small><b>${money(s.total)}</b></span><span><small>Outstanding</small><b>${money(s.outstanding)}</b></span></div><div class="customer-actions"><button type="button" data-customer-action="history" data-customer-id="${esc(c.id)}">History</button><button type="button" data-customer-action="edit" data-customer-id="${esc(c.id)}">Edit</button></div></article>`}).join(""): `<div class="empty-state customer-empty"><div class="empty-icon">♙</div><h4>${q?"No customers found":"No customers yet"}</h4><p>${q?"Try a different search.":"Add a customer or create an invoice with a customer to build your directory."}</p></div>`;}
  function openForm(id){const c=customers().find(x=>x.id===id)||{name:"",phone:"",email:"",address:"",gstin:""};document.getElementById("customer-modal-root").innerHTML=`<div class="customer-modal" data-customer-modal><div class="customer-dialog"><div class="modal-head"><div><span class="eyebrow">Customer</span><h3>${id?"Edit customer":"Add customer"}</h3></div><button type="button" data-customer-action="close">×</button></div><form id="customer-form"><input type="hidden" name="id" value="${esc(c.id||"")}"><label>Name<input name="name" required value="${esc(c.name)}" placeholder="Customer name"></label><label>Phone<input name="phone" value="${esc(c.phone)}" placeholder="Phone number" inputmode="tel"></label><label>Email<input name="email" type="email" value="${esc(c.email)}" placeholder="Email address"></label><label>Address<textarea name="address" rows="3" placeholder="Address">${esc(c.address||"")}</textarea></label><label>GSTIN<input name="gstin" value="${esc(c.gstin||"")}" placeholder="Optional GSTIN"></label><div class="modal-actions"><button type="button" data-customer-action="close">Cancel</button><button class="primary-btn" type="submit">Save customer</button></div></form></div></div>`;}
  function saveCustomer(form){const fd=new FormData(form),id=String(fd.get("id")||"")||`customer-${Date.now()}`,b=business();if(!b)return;const record={id,name:String(fd.get("name")||"").trim(),phone:String(fd.get("phone")||"").trim(),email:String(fd.get("email")||"").trim(),address:String(fd.get("address")||"").trim(),gstin:String(fd.get("gstin")||"").trim(),updatedAt:new Date().toISOString()};if(!record.name)return;const contacts=Array.isArray(b.contacts)?[...b.contacts]:[],idx=contacts.findIndex(x=>x.id===id);if(idx>=0)contacts[idx]={...contacts[idx],...record};else contacts.push({...record,createdAt:new Date().toISOString()});window.AppState.updateBusiness({contacts});window.AppState.save();document.querySelector("[data-customer-modal]")?.remove();render();window.toast?.("Customer saved");}
  document.addEventListener("click",e=>{const b=e.target.closest("[data-customer-action]");if(!b)return;const a=b.dataset.customerAction;if(a==="add"||a==="edit"){openForm(a==="edit"?b.dataset.customerId:null);return;}if(a==="close"){document.querySelector("[data-customer-modal]")?.remove();return;}if(a==="history"){const c=customers().find(x=>x.id===b.dataset.customerId);if(c){window.location.hash="invoices";setTimeout(()=>window.toast?.(`Viewing invoices for ${c.name}`),50);}}});
  document.addEventListener("submit",e=>{if(e.target.id==="customer-form"){e.preventDefault();saveCustomer(e.target);}});document.addEventListener("input",e=>{if(e.target.id==="customer-search")render();});
  window.AppCustomers=Object.freeze({view,render,customers});
})();
