/* OrbitBiz workspace — pure view/render helpers. */
(() => {
  "use strict";
  const core = window.OrbitBiz = window.OrbitBiz || {};
  const w = core.workspace = core.workspace || {};
  const {esc, icon, money, meta, nav} = w;

  w.metric = (label, value, note, tone, ic) => `<article class="ob-metric ${tone}"><div class="ob-metric-top"><span>${label}</span><i>${icon(ic)}</i></div><strong>${value}</strong><small>${note}</small></article>`;

  w.layout = (state) => {
    const [title, desc] = meta[state.page] || meta.dashboard;
    const user = state.user || core.auth?.currentUser;
    const name = user?.email?.split("@")[0] || "Workspace";
    return `<div class="ob-workspace"><aside class="ob-sidebar"><div class="ob-side-brand"><div class="ob-side-mark">O</div><div><b>OrbitBiz</b><span>by Orbit East</span></div></div><div class="ob-side-business"><span>WORKSPACE</span><strong>${esc(name)}</strong><i>●</i></div><nav class="ob-nav">${nav.map(([label, items]) => `<div class="ob-nav-group"><small>${label}</small>${items.map(([key, text]) => `<button class="ob-nav-item ${state.page === key ? "active" : ""}" data-page="${key}">${icon(key)}<span>${text}</span></button>`).join("")}</div>`).join("")}</nav><div class="ob-side-bottom"><button data-action="signout">${icon("arrow")} Sign out</button></div></aside><main class="ob-main"><header class="ob-topbar"><div class="ob-page-heading"><span>OrbitBiz / ${title}</span><h1>${title}</h1><p>${desc}</p></div><div class="ob-top-actions"><button class="ob-icon-btn" data-action="search" aria-label="Search">${icon("search")}</button><button class="ob-user-pill"><span>${esc(name.charAt(0).toUpperCase())}</span><b>${esc(name)}</b></button></div></header><div class="ob-content" id="workspace-content"><div class="ob-loading"><span></span><span></span><span></span></div></div></main></div>`;
  };

  w.table = (title, subtitle, rows, cols, emptyTitle, emptyText, action) => `<article class="ob-panel ob-full-panel"><div class="ob-panel-head"><div><span>${title.toUpperCase()}</span><h3>${subtitle}</h3></div><button class="ob-primary small" data-action="${action}">${icon("plus")} Add</button></div>${rows.length ? `<div class="ob-table-scroll"><table class="ob-table"><thead><tr>${cols.map(c => `<th>${c[0]}</th>`).join("")}</tr></thead><tbody>${rows.map(row => `<tr>${cols.map(col => `<td>${typeof col[1] === "function" ? col[1](row) : esc(row[col[1]] || "—")}</td>`).join("")}</tr>`).join("")}</tbody></table></div>` : `<div class="ob-empty"><div>${icon(action === "new-customer" ? "customers" : action === "new-item" ? "inventory" : "invoices")}</div><h4>${emptyTitle}</h4><p>${emptyText}</p><button class="ob-soft" data-action="${action}">${icon("plus")} Get started</button></div>`}</article>`;

  w.dashboardView = (data) => {
    const {customers, items, invoices, payments} = data;
    const sales = invoices.reduce((sum, row) => sum + Number(row.total || 0), 0);
    const paid = invoices.reduce((sum, row) => sum + Number(row.amount_paid || 0), 0);
    const received = payments.reduce((sum, row) => sum + Number(row.amount || 0), 0);
    const outstanding = Math.max(0, sales - paid);
    const recent = [...invoices].sort((a,b) => new Date(b.created_at || 0) - new Date(a.created_at || 0)).slice(0,5);
    return `<div class="ob-welcome"><div><span class="ob-eyebrow">TODAY'S OVERVIEW</span><h2>Everything important,<br><em>in one orbit.</em></h2><p>Track movement without digging through menus.</p></div><button class="ob-primary" data-action="quick-add">${icon("plus")} New transaction</button></div><section class="ob-metrics">${w.metric("Sales",money(sales),`${invoices.length} invoice${invoices.length === 1 ? "" : "s"}`,"yellow","finance")}${w.metric("Receivables",money(outstanding),"Still to collect","blue","invoices")}${w.metric("Received",money(received || paid),"Recorded payments","green","finance")}${w.metric("Customers",customers.length,`${items.length} items in catalogue`,"pink","customers")}</section><section class="ob-dashboard-grid"><article class="ob-panel ob-activity"><div class="ob-panel-head"><div><span>SALES FLOW</span><h3>Recent invoices</h3></div><button data-page="invoices">View all ${icon("arrow")}</button></div>${recent.length ? `<div class="ob-list">${recent.map((row,i) => `<div class="ob-list-row"><div class="ob-list-avatar tone-${i % 4}">${esc((row.invoice_number || "INV").slice(0,2))}</div><div class="ob-list-main"><strong>${esc(row.invoice_number || "Invoice")}</strong><small>${esc(row.status || "Recorded")}</small></div><b>${money(row.total)}</b><span class="ob-status ${Number(row.amount_paid || 0) >= Number(row.total || 0) ? "done" : "open"}">${Number(row.amount_paid || 0) >= Number(row.total || 0) ? "Paid" : "Open"}</span></div>`).join("")}</div>` : `<div class="ob-empty"><div>${icon("invoices")}</div><h4>No invoices yet</h4><p>Create your first invoice and your sales flow will appear here.</p><button class="ob-soft" data-page="invoices">Create invoice ${icon("arrow")}</button></div>`}</article><article class="ob-panel ob-focus"><div class="ob-panel-head"><div><span>QUICK ACTIONS</span><h3>Keep moving</h3></div>${icon("spark")}</div><div class="ob-action-grid"><button data-action="new-customer"><i class="tone-pink">${icon("customers")}</i><b>Customer</b><small>Add a relationship</small></button><button data-action="quick-invoice"><i class="tone-yellow">${icon("invoices")}</i><b>Invoice</b><small>Record a sale</small></button><button data-page="inventory"><i class="tone-green">${icon("inventory")}</i><b>Stock</b><small>Check inventory</small></button><button data-page="reports"><i class="tone-blue">${icon("reports")}</i><b>Report</b><small>See performance</small></button></div></article></section>`;
  };

  w.customersView = rows => w.table("Directory", `${rows.length} customer${rows.length === 1 ? "" : "s"}`, rows, [["Name",r => `<strong>${esc(r.name)}</strong>`],["Company",r => esc(r.company_name)],["Phone",r => esc(r.phone)],["Email",r => esc(r.email)],["Status",() => `<span class="ob-status done">Active</span>`]], "No customers yet", "Add a customer to start building your business directory.", "new-customer");
  w.inventoryView = rows => w.table("Catalogue", `${rows.length} item${rows.length === 1 ? "" : "s"}`, rows, [["Item",r => `<strong>${esc(r.name)}</strong>`],["SKU","sku"],["Type","item_type"],["Sale price",r => money(r.selling_price)],["Stock",r => Number(r.opening_stock || 0)]], "Your catalogue is empty", "Add products or services so sales and stock can connect.", "new-item");
  w.invoicesView = rows => w.table("Sales", `${rows.length} invoice${rows.length === 1 ? "" : "s"}`, rows, [["Invoice",r => `<strong>${esc(r.invoice_number || "Invoice")}</strong>`],["Total",r => money(r.total)],["Paid",r => money(r.amount_paid)],["Balance",r => money(Math.max(0, Number(r.total || 0) - Number(r.amount_paid || 0)))],["Status",r => `<span class="ob-status ${Number(r.amount_paid || 0) >= Number(r.total || 0) ? "done" : "open"}">${esc(r.status || (Number(r.amount_paid || 0) >= Number(r.total || 0) ? "Paid" : "Open"))}</span>`]], "No invoices yet", "Your sales documents will appear here once you create the first one.", "quick-invoice");

  w.genericView = page => { const [title, description] = meta[page] || meta.dashboard; return `<article class="ob-feature"><div class="ob-feature-art">${icon(page === "crm" ? "crm" : page === "finance" ? "finance" : page === "reports" ? "reports" : "spark")}</div><span class="ob-eyebrow">${title.toUpperCase()}</span><h2>${title}</h2><p>${description}</p><div class="ob-feature-line"><span>CONNECTED WORKSPACE</span><b>This area is being built on the same live business foundation.</b></div><button class="ob-primary" data-action="quick-add">${icon("plus")} Start here</button></article>`; };
})();
