(() => {
  "use strict";
  const root = document.querySelector("#app");
  if (!root) return;
  const sections = [
    {title:"Sales",items:[["Dashboard","dashboard","dashboard"],["Sales CRM & Leads","crm","crm",true],["Clients & Vendors","clients","clients",true],["Invoices","invoices","invoice"],["Quotations","quotations","quote"],["Proforma Invoices","proforma","invoice"],["Payment Receipts","receipts","receipt"]]},
    {title:"Purchases & Expenses",items:[["Purchases & Expenses","purchases","purchase",true],["Purchase Orders","purchase-orders","orders"],["Vendor Payments","vendor-payments","payment"]]},
    {title:"Inventory",items:[["Items & Services","items","inventory"],["Stock","stock","stock"],["Warehouses","warehouses","warehouse"]]},
    {title:"Reports",items:[["Business Reports","reports","reports"],["GST Reports","gst","tax"],["Accounting Reports","accounting-reports","reports"]]},
    {title:"Bank & Payments",items:[["Payment Accounts","payment-accounts","bank"],["Bank Reconciliation","reconciliation","reconcile"]]}
  ];
  const icon=name=>{const p={dashboard:'<rect x="4" y="4" width="6" height="7" rx="1"/><rect x="14" y="4" width="6" height="4" rx="1"/><rect x="14" y="12" width="6" height="8" rx="1"/><rect x="4" y="15" width="6" height="5" rx="1"/>',crm:'<circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 5a3 3 0 0 1 0 6M16 14a5 5 0 0 1 5 5"/>',clients:'<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2.5 20a5.5 5.5 0 0 1 11 0M14 20a4.5 4.5 0 0 1 7 0"/>',invoice:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6M9 15h4"/>',quote:'<path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h5M8 16h8"/>',receipt:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6M9 16h3"/>',purchase:'<path d="M4 5h2l2 11h9l2-8H7"/><circle cx="10" cy="20" r="1"/><circle cx="17" cy="20" r="1"/>',orders:'<path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h6M8 16h4"/>',payment:'<path d="M3 7h18v12H3z"/><path d="M3 10h18M7 15h4"/>',inventory:'<path d="m12 3 8 4-8 4-8-4 8-4Z"/><path d="M4 11v8l8 4 8-4v-8M12 11v12"/>',stock:'<path d="M4 7h16v13H4z"/><path d="M4 11h16M8 7V4h8v3"/>',warehouse:'<path d="m3 10 9-6 9 6v10H3z"/><path d="M9 20v-6h6v6"/>',reports:'<path d="M4 19V5M4 19h16"/><path d="M8 16v-5M12 16V7M16 16v-3M20 16V4"/>',gst:'<path d="M6 3h12v18H6z"/><path d="M9 8h6M9 12h6M9 16h4"/>',tax:'<path d="M5 5h14v14H5z"/><path d="m8 16 8-8M9 9h.01M15 15h.01"/>',bank:'<path d="m3 10 9-6 9 6"/><path d="M5 10v8M9 10v8M15 10v8M19 10v8M3 20h18"/>',reconcile:'<path d="M4 7h12a4 4 0 0 1 0 8H7"/><path d="m7 11-3 4 3 4"/><path d="M20 17H8a4 4 0 0 1 0-8h9"/><path d="m17 5 3 4-3 4"/>',search:'<circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/>',bell:'<path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.6 9a2.5 2.5 0 1 1 4.1 1.9c-1.1.9-1.7 1.3-1.7 2.8M12 17h.01"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1.2l2-1.5-2-3.4-2.4 1a8 8 0 0 0-2-1.2L14.2 3h-4.1l-.4 2.7a8 8 0 0 0-2 1.2l-2.4-1-2 3.4 2 1.5A7 7 0 0 0 5.2 12c0 .4 0 .8.1 1.2l-2 1.5 2.4 3.4 2.4-1a8 8 0 0 0 2 1.2l.4 2.7h4.1l.4-2.7a8 8 0 0 0 2-1.2l2.4 1-2.4-3.4-2-1.5c.1-.4.1-.8.1-1.2Z"/>',plus:'<path d="M12 5v14M5 12h14"/>',filter:'<path d="M4 6h16M7 12h10M10 18h4"/>',arrow:'<path d="M5 12h13M13 6l6 6-6 6"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${p[name]||p.dashboard}</svg>`};
  const navItem=(label,key,ico,active=false,expand=false)=>`<button class="ref-nav-item ${active?'active':''}" data-nav="${key}"><span class="ref-nav-icon">${icon(ico)}</span><span>${label}</span>${expand?'<span class="ref-nav-chevron">⌄</span>':''}</button>`;
  function sidebar(){return `<aside class="ref-sidebar"><div class="ref-brand"><button class="ref-menu" aria-label="Menu">☰</button><span class="orbit-mini-logo"></span><strong>Orbit</strong><small>BizAssist</small></div><div class="ref-workspace"><span class="ref-workspace-logo">O</span><span><b>Your business</b><small>Books &amp; CRM</small></span><span class="ref-workspace-caret">⌄</span></div><nav class="ref-nav">${sections.map(s=>`<div class="ref-nav-section">${s.title}</div>${s.items.map(([l,k,i,e])=>navItem(l,k,i,k==='dashboard',e)).join('')}`).join('')}<button class="ref-more-link">See more <span>⌄</span></button></nav><div class="ref-sidebar-bottom">${navItem('Settings','settings','settings')}<div class="ref-user"><span class="ref-avatar">N</span><span><b>Nayanjyoti Ghosh</b><small>Owner</small></span><span class="ref-user-more">•••</span></div></div></aside>`}
  function topbar(){return `<header class="ref-topbar"><div class="ref-top-search"><span>${icon('search')}</span><input placeholder="Search invoices, clients, products…" aria-label="Search"/><kbd>⌘ K</kbd></div><div class="ref-top-actions"><button class="ref-help">${icon('help')} Help</button><button class="ref-icon-btn" aria-label="Notifications">${icon('bell')}<i></i></button><span class="ref-separator"></span><button class="ref-profile"><span class="ref-avatar small">N</span><span>Nayanjyoti</span><span>⌄</span></button></div></header>`}
  function stat(label,value,tone,note,symbol){return `<div class="ref-stat"><div class="ref-stat-label"><span>${label}</span><span class="ref-stat-icon ${tone}">${symbol}</span></div><strong>${value}</strong><small>${note}</small></div>`}
  function dashboard(){return `<section class="ref-content"><div class="ref-breadcrumb"><span>Dashboard</span><b>/</b> Overview</div><div class="ref-page-head"><div><h1>Dashboard</h1><p>Track your business at a glance.</p></div><button class="ref-primary">${icon('plus')} Create new <span>⌄</span></button></div><div class="ref-filterbar"><button>FY 2026–27 <span>⌄</span></button><button>${icon('filter')} Filters <b>0</b></button><span></span><button class="ref-view-toggle">Overview</button><button class="ref-more-button">•••</button></div><div class="ref-summary"><div class="ref-summary-title"><b>Summary &amp; Graph</b><button>Hide summary</button></div><div class="ref-stats">${stat('Total Sales','₹0','blue','No sales yet','₹')}${stat('Receivables','₹0','purple','Nothing outstanding','↗')}${stat('Expenses','₹0','orange','No expenses recorded','−')}${stat('Stock Value','₹0','green','No inventory yet','□')}</div></div><div class="ref-grid"><div class="ref-panel ref-chart-panel"><div class="ref-panel-head"><div><b>Sales overview</b><small>Revenue movement across the selected period</small></div><button>Monthly ⌄</button></div><div class="ref-chart"><div class="ref-gridline g1"></div><div class="ref-gridline g2"></div><div class="ref-gridline g3"></div><div class="ref-gridline g4"></div><div class="ref-chart-empty"><span class="ref-empty-orbit">◎</span><b>No sales data yet</b><small>Create your first invoice and your business trend will appear here.</small></div><div class="ref-axis"><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div></div></div><div class="ref-panel ref-activity"><div class="ref-panel-head"><div><b>Recent activity</b><small>Latest business events</small></div><button>View all ${icon('arrow')}</button></div><div class="ref-empty-list"><div class="ref-empty-icon">${icon('invoice')}</div><b>No activity yet</b><small>Invoices, payments and updates will appear here.</small></div></div></div><div class="ref-panel ref-start"><div><b>Get started with Orbit</b><small>Complete your business setup to unlock your workspace.</small></div><div class="ref-start-actions"><button>Add business details</button><button>Add your first customer</button><button>Create an invoice ${icon('arrow')}</button></div></div></section>`}
  function render(){root.innerHTML=`<div class="ref-app">${sidebar()}<div class="ref-main">${topbar()}<main>${dashboard()}</main></div></div>`;root.querySelectorAll('[data-nav]').forEach(btn=>btn.addEventListener('click',()=>{root.querySelectorAll('.ref-nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}))}
  render();
})();
