/* Orbit Biz — dashboard analytics UX */
(()=>{
"use strict";
let mounted=false,loading=false;
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const client=()=>window.OrbitBiz?.auth?.getClient?.()||window.supabase?.createClient?.(window.OrbitBiz?.config?.supabaseUrl,window.OrbitBiz?.config?.supabaseKey);
const dates=range=>{const end=new Date();end.setHours(23,59,59,999);const start=new Date(end);if(range==="7d")start.setDate(start.getDate()-6);else if(range==="30d")start.setDate(start.getDate()-29);else if(range==="90d")start.setDate(start.getDate()-89);else start.setDate(start.getDate()-364);return [start.toISOString(),end.toISOString()]};
async function load(range){if(loading)return;const id=localStorage.getItem("orbitbiz.activeBusinessId");const db=client();if(!id||!db)return;loading=true;try{const [a,b,c]=dates(range);const [iv,ex]=await Promise.all([db.from("invoices").select("id,total,amount_paid,issue_date,status").eq("business_id",id).gte("issue_date",a.slice(0,10)).lte("issue_date",b.slice(0,10)),db.from("expenses").select("id,amount,expense_date").eq("business_id",id).gte("expense_date",a.slice(0,10)).lte("expense_date",b.slice(0,10))]);if(iv.error)throw iv.error;if(ex.error)throw ex.error;const invoices=iv.data||[],expenses=ex.data||[];const sales=invoices.reduce((n,x)=>n+Number(x.total||0),0),paid=invoices.reduce((n,x)=>n+Number(x.amount_paid||0),0),cost=expenses.reduce((n,x)=>n+Number(x.amount||0),0),profit=sales-cost;const panel=document.querySelector("#workspace-content .workspace-grid");if(!panel)return;panel.innerHTML=`<div class="wb-card"><span>Sales</span><strong>${money(sales)}</strong><small>${invoices.length} invoice${invoices.length===1?"":"s"}</small></div><div class="wb-card"><span>Receivables</span><strong>${money(Math.max(0,sales-paid))}</strong><small>Outstanding in selected period</small></div><div class="wb-card"><span>Expenses</span><strong>${money(cost)}</strong><small>${expenses.length} record${expenses.length===1?"":"s"}</small></div><div class="wb-card"><span>Net result</span><strong>${money(profit)}</strong><small>${profit>=0?"Positive result":"Loss in selected period"}</small></div>`;mounted=true}catch(e){console.error("Dashboard analytics",e)}finally{loading=false}}
function mount(){if(mounted||document.querySelector("[data-dashboard-ux]"))return;const content=document.querySelector("#workspace-content");if(!content||!document.querySelector(".workspace-topbar h1"))return;if(document.querySelector(".workspace-topbar h1")?.textContent.trim()!=="Dashboard")return;const bar=document.createElement("div");bar.dataset.dashboardUx="1";bar.className="dashboard-filterbar";bar.innerHTML=`<div><strong>Performance</strong><span>Choose a period to view live numbers</span></div><div class="dashboard-ranges"><button data-range="7d">7 days</button><button class="active" data-range="30d">30 days</button><button data-range="90d">90 days</button><button data-range="1y">1 year</button></div>`;const grid=content.querySelector(".workspace-grid");if(!grid)return;content.insertBefore(bar,grid);bar.querySelectorAll("button").forEach(b=>b.onclick=()=>{bar.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active");mounted=false;load(b.dataset.range)});load("30d")}
new MutationObserver(()=>mount()).observe(document.body,{childList:true,subtree:true});setTimeout(mount,250);window.addEventListener("orbitbiz:auth-ready",()=>{mounted=false;setTimeout(mount,250)});window.addEventListener("auth:ready",()=>{mounted=false;setTimeout(mount,250)});
})();
