/* Orbit Biz — unified production feature layer */
(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date=()=>new Date().toISOString().slice(0,10);
const cfg=()=>window.OrbitBiz?.config||{};
const db=()=>window.OrbitBiz?.auth?.getClient?.()||window.supabase?.createClient?.(cfg().supabaseUrl,cfg().supabaseKey);
const bid=()=>localStorage.getItem('orbitbiz.activeBusinessId')||'';
const toast=m=>window.toast?window.toast(m):document.querySelector('.wb-toast')?.textContent=m;
const page=()=>document.querySelector('.workspace-nav-item.active')?.dataset?.page||'';
let rendering=false,lastPage='';
async function rows(table,select='*'){const r=await db().from(table).select(select).eq('business_id',bid()).order('created_at',{ascending:false}).limit(200);if(r.error)throw r.error;return r.data||[]}
function shell(title,sub,action,label){return `<div class="wb-panel"><div class="wb-panel-head"><div><h2>${title}</h2><p>${sub}</p></div>${action?`<button class="wb-btn primary" data-suite-add="${action}">＋ ${label||'Add'}</button>`:''}</div><div id="suite-body"><div class="wb-empty"><p>Loading…</p></div></div></div>`}
function table(headers,body){return `<div class="wb-table-wrap"><table class="wb-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${headers.length}"><div class="wb-empty"><h3>No records yet</h3></div></td></tr>`}</tbody></table></div>`}
function modal(title,subtitle,form,onSave){const old=document.querySelector('.suite-modal');old?.remove();const x=document.createElement('div');x.className='wb-modal suite-modal';x.innerHTML=`<div class="wb-modal-backdrop" data-close></div><div class="wb-modal-card suite-card"><div class="wb-modal-head"><div><h2>${title}</h2><p>${subtitle}</p></div><button class="wb-modal-close" data-close>×</button></div><form class="suite-form">${form}<div class="suite-actions"><button type="button" class="wb-btn" data-close>Cancel</button><button class="wb-btn primary" type="submit">Save</button></div></form></div>`;document.body.appendChild(x);x.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>x.remove());x.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=x.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Saving…';try{await onSave(new FormData(e.target));x.remove();toast('Saved successfully');await render(true)}catch(err){toast(err.message||'Could not save');btn.disabled=false;btn.textContent='Save'}};return x}
const input=(l,n,t='text',v='',attrs='')=>`<div class="wb-field"><label>${l}</label><input name="${n}" type="${t}" value="${esc(v)}" ${attrs}></div>`;
const select=(l,n,opts,v='')=>`<div class="wb-field"><label>${l}</label><select name="${n}"><option value="">Select</option>${opts.map(o=>`<option value="${esc(o.id)}" ${o.id===v?'selected':''}>${esc(o.name||o.company_name||o.id)}</option>`).join('')}</select></div>`;
async function customers(){const r=await rows('customers');document.querySelector('#suite-body').innerHTML=r.length?table(['Customer','Company','Phone','Email','Balance','Status',''],r.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.company_name||'—')}</td><td>${esc(x.phone||'—')}</td><td>${esc(x.email||'—')}</td><td>${money(x.opening_balance)}</td><td><span class="wb-badge paid">Active</span></td><td><button class="wb-btn small" data-edit-customer="${x.id}">Edit</button></td></tr>`).join('')):`<div class="wb-empty"><h3>No customers yet</h3><p>Add your first customer.</p></div>`;document.querySelectorAll('[data-edit-customer]').forEach(b=>b.onclick=()=>editCustomer(r.find(x=>x.id===b.dataset.editCustomer)))}
function editCustomer(x){modal(x?'Edit customer':'Add customer','Customer profile',`${input('Customer name *','name','text',x?.name||'','required')}${input('Company','company_name','text',x?.company_name||'')}${input('Phone','phone','tel',x?.phone||'')}${input('Email','email','email',x?.email||'')}${input('GSTIN','gstin','text',x?.gstin||'')}${input('Opening balance','opening_balance','number',x?.opening_balance||0,'step=0.01')}${input('Credit limit','credit_limit','number',x?.credit_limit||'','step=0.01')}`,async f=>{const p={business_id:bid(),name:String(f.get('name')).trim(),company_name:String(f.get('company_name')||'').trim()||null,phone:String(f.get('phone')||'').trim()||null,email:String(f.get('email')||'').trim()||null,gstin:String(f.get('gstin')||'').trim().toUpperCase()||null,opening_balance:Number(f.get('opening_balance')||0),credit_limit:Number(f.get('credit_limit')||0)||null};const q=x?db().from('customers').update(p).eq('id',x.id).eq('business_id',bid()):db().from('customers').insert(p);const r=await q;if(r.error)throw r.error})}
async function vendors(){const r=await rows('vendors');document.querySelector('#suite-body').innerHTML=table(['Vendor','Company','Phone','Email','Opening balance',''],r.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.company_name||'—')}</td><td>${esc(x.phone||'—')}</td><td>${esc(x.email||'—')}</td><td>${money(x.opening_balance)}</td><td><button class="wb-btn small" data-vendor="${x.id}">Edit</button></td></tr>`).join(''));document.querySelectorAll('[data-vendor]').forEach(b=>b.onclick=()=>vendorModal(r.find(x=>x.id===b.dataset.vendor)))}
function vendorModal(x){modal(x?'Edit vendor':'Add vendor','Supplier profile',`${input('Vendor name *','name','text',x?.name||'','required')}${input('Company','company_name','text',x?.company_name||'')}${input('Phone','phone','tel',x?.phone||'')}${input('Email','email','email',x?.email||'')}${input('GSTIN','gstin','text',x?.gstin||'')}${input('Opening balance','opening_balance','number',x?.opening_balance||0,'step=0.01')}`,async f=>{const p={business_id:bid(),name:String(f.get('name')).trim(),company_name:String(f.get('company_name')||'').trim()||null,phone:String(f.get('phone')||'').trim()||null,email:String(f.get('email')||'').trim()||null,gstin:String(f.get('gstin')||'').trim().toUpperCase()||null,opening_balance:Number(f.get('opening_balance')||0)};const r=x?await db().from('vendors').update(p).eq('id',x.id).eq('business_id',bid()):await db().from('vendors').insert(p);if(r.error)throw r.error})}
async function expenses(){const [r,v]=await Promise.all([rows('expenses'),rows('vendors','id,name')]);document.querySelector('#suite-body').innerHTML=table(['Date','Category','Description','Vendor','Amount','Method',''],r.map(x=>`<tr><td>${esc(x.expense_date)}</td><td>${esc(x.category||'—')}</td><td>${esc(x.description||'—')}</td><td>${esc(v.find(z=>z.id===x.vendor_id)?.name||'—')}</td><td><strong>${money(x.amount)}</strong></td><td>${esc(x.payment_method||'—')}</td><td></td></tr>`).join(''))}
async function payments(){const [r,c,i]=await Promise.all([rows('payments'),rows('customers','id,name'),rows('invoices','id,invoice_number')]);document.querySelector('#suite-body').innerHTML=table(['Date','Customer','Invoice','Amount','Method','Reference'],r.map(x=>`<tr><td>${esc(x.payment_date)}</td><td>${esc(c.find(z=>z.id===x.customer_id)?.name||'—')}</td><td>${esc(i.find(z=>z.id===x.invoice_id)?.invoice_number||'—')}</td><td><strong>${money(x.amount)}</strong></td><td>${esc(x.method||'—')}</td><td>${esc(x.reference||'—')}</td></tr>`).join(''))}
async function accounts(){const r=await rows('payment_accounts');document.querySelector('#suite-body').innerHTML=table(['Account','Type','Opening','Current','Status',''],r.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.account_type||'—')}</td><td>${money(x.opening_balance)}</td><td>${money(x.current_balance)}</td><td><span class="wb-badge paid">Active</span></td><td><button class="wb-btn small" data-account="${x.id}">Edit</button></td></tr>`).join(''));document.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>accountModal(r.find(x=>x.id===b.dataset.account)))}
function accountModal(x){modal(x?'Edit payment account':'Add payment account','Cash, bank or digital account',`${input('Account name *','name','text',x?.name||'','required')}${input('Account type','account_type','text',x?.account_type||'cash')}${input('Opening balance','opening_balance','number',x?.opening_balance||0,'step=0.01')}`,async f=>{const p={business_id:bid(),name:String(f.get('name')).trim(),account_type:String(f.get('account_type')||'cash').trim(),opening_balance:Number(f.get('opening_balance')||0)};if(x){const r=await db().from('payment_accounts').update(p).eq('id',x.id).eq('business_id',bid());if(r.error)throw r.error}else{p.current_balance=p.opening_balance;const r=await db().from('payment_accounts').insert(p);if(r.error)throw r.error}})}
async function stock(){const [it,m]=await Promise.all([rows('items'),rows('stock_movements')]);const qty=id=>Number(it.find(x=>x.id===id)?.opening_stock||0)+m.filter(x=>x.item_id===id).reduce((a,x)=>a+Number(x.quantity||0),0);document.querySelector('#suite-body').innerHTML=table(['Item','SKU','Stock','Reorder level','Status',''],it.map(x=>{const q=qty(x.id),low=q<=Number(x.reorder_level||0);return `<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.sku||'—')}</td><td>${q}</td><td>${Number(x.reorder_level||0)}</td><td><span class="wb-badge ${low?'overdue':'paid'}">${low?'Low stock':'Healthy'}</span></td><td><button class="wb-btn small" data-stock="${x.id}">Adjust</button></td></tr>`}).join(''));document.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>stockModal(it.find(x=>x.id===b.dataset.stock),qty(b.dataset.stock)))}
function stockModal(x,current){modal('Adjust stock',x.name,`${input('New stock quantity','quantity','number',current,'step=0.01 min=0 required')}${input('Note','notes','text','','')}`,async f=>{const target=Number(f.get('quantity')||0),delta=target-current;if(!delta)return;const r=await db().from('stock_movements').insert({business_id:bid(),item_id:x.id,quantity:delta,movement_type:'adjustment',notes:String(f.get('notes')||'').trim()||'Manual stock adjustment'});if(r.error)throw r.error})}
async function warehouses(){const r=await rows('warehouses');document.querySelector('#suite-body').innerHTML=table(['Name','Code','Status','Created',''],r.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.code||'—')}</td><td><span class="wb-badge paid">Active</span></td><td>${esc(x.created_at?.slice(0,10)||'')}</td><td><button class="wb-btn small" data-wh="${x.id}">Edit</button></td></tr>`).join(''));document.querySelectorAll('[data-wh]').forEach(b=>b.onclick=()=>warehouseModal(r.find(x=>x.id===b.dataset.wh)))}
function warehouseModal(x){modal(x?'Edit warehouse':'Add warehouse','Stock location',`${input('Warehouse name *','name','text',x?.name||'','required')}${input('Code','code','text',x?.code||'')}${input('Address','address','text',typeof x?.address==='string'?x.address:'')}`,async f=>{const p={business_id:bid(),name:String(f.get('name')).trim(),code:String(f.get('code')||'').trim()||null,address:{text:String(f.get('address')||'').trim()||null}};const r=x?await db().from('warehouses').update(p).eq('id',x.id).eq('business_id',bid()):await db().from('warehouses').insert(p);if(r.error)throw r.error})}
async function genericDoc(kind){const map={quotations:['quotations','quote_number','Quotations','quotation'],proforma:['proforma_invoices','proforma_number','Proforma invoices','proforma'], 'purchase-orders':['purchase_orders','po_number','Purchase orders','purchase_order']};const [table,num,title]=map[kind];const [r,c,v]=await Promise.all([rows(table),rows('customers','id,name').catch(()=>[]),rows('vendors','id,name').catch(()=>[])]);const people=kind==='purchase-orders'?v:c;document.querySelector('#suite-body').innerHTML=tableFn(title,r,num,people);document.querySelector('[data-suite-add]')?.addEventListener('click',()=>docModal(kind,people))}
function tableFn(title,r,num,people){return table(['Number','Party','Date','Status','Subtotal','Tax','Total',''],r.map(x=>`<tr><td><strong>${esc(x[num])}</strong></td><td>${esc(people.find(p=>p.id===x.customer_id||p.id===x.vendor_id)?.name||'—')}</td><td>${esc(x.issue_date||x.order_date||'')}</td><td><span class="wb-badge ${x.status==='paid'?'paid':'pending'}">${esc(x.status||'draft')}</span></td><td>${money(x.subtotal)}</td><td>${money(x.tax_total)}</td><td><strong>${money(x.total)}</strong></td><td></td></tr>`).join(''))}
async function receipts(){const [r,c]=await Promise.all([rows('receipts'),rows('customers','id,name')]);document.querySelector('#suite-body').innerHTML=table(['Receipt','Date','Customer','Amount','Method','Reference'],r.map(x=>`<tr><td><strong>${esc(x.receipt_number)}</strong></td><td>${esc(x.receipt_date)}</td><td>${esc(c.find(z=>z.id===x.customer_id)?.name||'—')}</td><td>${money(x.amount)}</td><td>${esc(x.method||'—')}</td><td>${esc(x.reference||'—')}</td></tr>`).join(''))}
async function reports(){const [iv,ex,py]=await Promise.all([rows('invoices'),rows('expenses'),rows('payments')]);const sales=iv.reduce((a,x)=>a+Number(x.total||0),0),paid=py.reduce((a,x)=>a+Number(x.amount||0),0),expenses=ex.reduce((a,x)=>a+Number(x.amount||0),0);document.querySelector('#suite-body').innerHTML=`<div class="workspace-grid">${`<div class="wb-card"><span>Sales</span><strong>${money(sales)}</strong><small>${iv.length} invoices</small></div>`}${`<div class="wb-card"><span>Collected</span><strong>${money(paid)}</strong><small>Recorded payments</small></div>`}${`<div class="wb-card"><span>Expenses</span><strong>${money(expenses)}</strong><small>${ex.length} records</small></div>`}${`<div class="wb-card"><span>Net movement</span><strong>${money(paid-expenses)}</strong><small>Collected minus expenses</small></div>`}</div>`}
async function gst(){const [iv,ex]=await Promise.all([rows('invoices'),rows('expenses')]);const taxOut=iv.reduce((a,x)=>a+Number(x.tax_total||0),0),taxIn=ex.reduce((a,x)=>a+Number(x.tax_amount||0),0);document.querySelector('#suite-body').innerHTML=`<div class="workspace-grid"><div class="wb-card"><span>Output tax</span><strong>${money(taxOut)}</strong><small>From sales invoices</small></div><div class="wb-card"><span>Input tax</span><strong>${money(taxIn)}</strong><small>From expenses</small></div><div class="wb-card"><span>Estimated net tax</span><strong>${money(taxOut-taxIn)}</strong><small>Output minus input</small></div></div><div class="wb-empty"><p>Use these figures as a workspace summary; statutory filing should be checked against your books and applicable GST rules.</p></div>`}
async function accounting(){const [iv,ex,py]=await Promise.all([rows('invoices'),rows('expenses'),rows('payments')]);const revenue=iv.reduce((a,x)=>a+Number(x.total||0),0),expense=ex.reduce((a,x)=>a+Number(x.amount||0),0),cash=py.reduce((a,x)=>a+Number(x.amount||0),0);document.querySelector('#suite-body').innerHTML=table(['Statement','Amount','Basis'],`<tr><td>Revenue</td><td>${money(revenue)}</td><td>Invoice totals</td></tr><tr><td>Expenses</td><td>${money(expense)}</td><td>Recorded expenses</td></tr><tr><td>Gross operating result</td><td>${money(revenue-expense)}</td><td>Revenue − expenses</td></tr><tr><td>Collections</td><td>${money(cash)}</td><td>Recorded customer payments</td></tr>`)}
async function reconciliation(){const [r,a]=await Promise.all([rows('reconciliations'),rows('payment_accounts','id,name')]);document.querySelector('#suite-body').innerHTML=table(['Date','Account','Statement','Book','Difference','Status'],r.map(x=>`<tr><td>${esc(x.reconciliation_date)}</td><td>${esc(a.find(z=>z.id===x.payment_account_id)?.name||'—')}</td><td>${money(x.statement_balance)}</td><td>${money(x.book_balance)}</td><td>${money(Number(x.statement_balance)-Number(x.book_balance))}</td><td>${esc(x.status)}</td></tr>`).join(''))}
async function crm(){const r=await rows('customers');document.querySelector('#suite-body').innerHTML=`<div class="workspace-grid">${`<div class="wb-card"><span>Customers</span><strong>${r.length}</strong><small>Total profiles</small></div>`}${`<div class="wb-card"><span>With phone</span><strong>${r.filter(x=>x.phone).length}</strong><small>Reachable contacts</small></div>`}${`<div class="wb-card"><span>With email</span><strong>${r.filter(x=>x.email).length}</strong><small>Email-ready contacts</small></div>`}${`<div class="wb-card"><span>Credit limits</span><strong>${money(r.reduce((a,x)=>a+Number(x.credit_limit||0),0))}</strong><small>Configured limits</small></div>`}</div>${table(['Customer','Company','Phone','Email','Credit limit'],r.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.company_name||'—')}</td><td>${esc(x.phone||'—')}</td><td>${esc(x.email||'—')}</td><td>${money(x.credit_limit)}</td></tr>`).join(''))}`}
async function settings(){const r=await db().from('businesses').select('*').eq('id',bid()).maybeSingle();if(r.error)throw r.error;const b=r.data||{};document.querySelector('#suite-body').innerHTML=`<form id="business-settings" class="suite-form">${input('Business name *','name','text',b.name||'','required')}${input('Business email','email','email',b.email||'')}${input('Business phone','phone','tel',b.phone||'')}${input('GSTIN','gstin','text',b.gstin||'')}${input('Currency','currency','text',b.currency||'INR')}<div class="suite-actions"><button class="wb-btn primary">Save business settings</button></div></form>`;document.querySelector('#business-settings').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),p={name:String(f.get('name')).trim(),email:String(f.get('email')||'').trim()||null,phone:String(f.get('phone')||'').trim()||null,gstin:String(f.get('gstin')||'').trim().toUpperCase()||null,currency:String(f.get('currency')||'INR').trim()};const q=await db().from('businesses').update(p).eq('id',bid());if(q.error)toast(q.error.message);else toast('Business settings saved')}}
async function docModal(kind,people){const map={quotations:['Quotation','quote_number','customer_id'],proforma:['Proforma invoice','proforma_number','customer_id'],'purchase-orders':['Purchase order','po_number','vendor_id']};const [title,num,person]=map[kind];modal(`New ${title}`,'Document header',`${input(`${title} number *`,num,'text',`${kind==='purchase-orders'?'PO':'DOC'}-${Date.now().toString().slice(-6)}`,'required')}${select(kind==='purchase-orders'?'Vendor':'Customer',person,people)}${input('Date','date','date',date(),'required')}${input('Total','total','number',0,'step=0.01 min=0')}${input('Notes','notes')}`,async f=>{const p={business_id:bid(),[num]:String(f.get(num)).trim(),[person]:String(f.get(person)||'')||null,status:'draft',notes:String(f.get('notes')||'').trim()||null};if(kind==='purchase-orders'){p.order_date=f.get('date');p.total=Number(f.get('total')||0);p.subtotal=p.total;p.tax_total=0}else{p.issue_date=f.get('date');p.total=Number(f.get('total')||0);p.subtotal=p.total;p.discount_total=0;p.tax_total=0}const r=await db().from(kind==='quotations'?'quotations':kind==='proforma'?'proforma_invoices':'purchase_orders').insert(p);if(r.error)throw r.error})}
async function render(force=false){const p=page();if(!bid()||rendering)return;if(!force&&p===lastPage&&document.querySelector('#suite-body'))return;lastPage=p;const content=document.querySelector('#workspace-content');if(!content)return;const configs={crm:['CRM','Customer relationships','crm',''],clients:['Customers','Customer profiles','customers','Add customer'],purchases:['Purchases','Supplier and purchase records',null], 'vendor-payments':['Vendor payments','Supplier payment records',null],receipts:['Receipts','Customer payment receipts',null],stock:['Stock','Live inventory quantities and movements','stock','Adjust stock'],warehouses:['Warehouses','Stock locations','warehouses','Add warehouse'],reports:['Reports','Business performance summaries','reports',''],gst:['GST','Tax workspace summary','gst',''], 'accounting-reports':['Accounting reports','Financial statements and summaries','accounting',''], 'payment-accounts':['Payment accounts','Cash, bank and digital balances','accounts','Add account'],reconciliation:['Reconciliation','Match statement and book balances','reconciliation','Add reconciliation'],settings:['Settings','Business and application settings','settings',''],quotations:['Quotations','Customer quotes','quotations','New quotation'],proforma:['Proforma invoices','Commercial draft invoices','proforma','New proforma'],'purchase-orders':['Purchase orders','Supplier orders','purchase-orders','New purchase order']};if(!configs[p])return;rendering=true;try{const c=configs[p];content.innerHTML=shell(c[0],c[1],c[2],c[3]);if(c[2]==='customers')await customers();else if(c[2]==='crm')await crm();else if(c[2]==='stock')await stock();else if(c[2]==='warehouses')await warehouses();else if(c[2]==='reports')await reports();else if(c[2]==='gst')await gst();else if(c[2]==='accounting')await accounting();else if(c[2]==='accounts')await accounts();else if(c[2]==='reconciliation')await reconciliation();else if(c[2]==='quotations'||c[2]==='proforma'||c[2]==='purchase-orders')await genericDoc(p);else if(p==='receipts')await receipts();else if(p==='settings')await settings();else if(p==='purchases')await expenses();else if(p==='vendor-payments')await payments();const add=document.querySelector('[data-suite-add]');if(add)add.onclick=()=>{if(c[2]==='customers')window.OrbitBiz?.customerUX?.open?.();else if(c[2]==='stock')toast('Use Adjust on an item to set its target stock');else if(c[2]==='warehouses')warehouseModal();else if(c[2]==='accounts')accountModal();else if(c[2]==='quotations'||c[2]==='proforma'||c[2]==='purchase-orders')db().from('customers').select('id,name').eq('business_id',bid()).then(r=>docModal(p,r.data||[]));else if(c[2]==='reconciliation')toast('Reconciliation entry form is available after account selection')};}catch(e){content.innerHTML=`<div class="wb-empty"><h3>Could not load this workspace</h3><p>${esc(e.message||'Database error')}</p><button class="wb-btn" onclick="location.reload()">Retry</button></div>`}finally{rendering=false}}
new MutationObserver(()=>{if(page()!==lastPage)setTimeout(()=>render(),0)}).observe(document.body,{childList:true,subtree:true});
document.addEventListener('orbitbiz:customer-added',()=>render(true));
window.OrbitBiz=window.OrbitBiz||{};window.OrbitBiz.featureSuite={refresh:()=>render(true)};
setTimeout(render,250);
})();
