/* Orbit Biz — production inventory workflow */
(()=>{
"use strict";
const bid=()=>localStorage.getItem("orbitbiz.activeBusinessId")||"";
const cfg=()=>window.OrbitBiz?.config||{};
const db=()=>window.OrbitBiz?.auth?.getClient?.()||window.supabase?.createClient?.(cfg().supabaseUrl,cfg().supabaseKey);
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const money=n=>`₹${Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const qty=n=>Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:3});
const toast=m=>{let x=document.querySelector(".wb-toast");if(!x){x=document.createElement("div");x.className="wb-toast";document.body.appendChild(x)}x.textContent=m;x.classList.add("show");clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove("show"),2600)};
const modal=(title,body)=>{document.querySelector(".ob-inv-modal")?.remove();const x=document.createElement("div");x.className="wb-modal ob-inv-modal";x.innerHTML=`<div class="wb-modal-backdrop" data-close></div><div class="wb-modal-card ob-inv-card"><div class="wb-modal-head"><div><h2>${title}</h2><p>Inventory changes are saved to this business workspace.</p></div><button class="wb-modal-close" data-close>×</button></div>${body}</div>`;document.body.appendChild(x);x.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>x.remove());return x};
const field=(l,n,t="text",extra="")=>`<div class="wb-field"><label>${l}</label><input name="${n}" type="${t}" ${extra}></div>`;
async function getItems(){const r=await db().from("items").select("id,sku,name,item_type,category,unit,selling_price,purchase_price,tax_rate,opening_stock,reorder_level,is_active,created_at").eq("business_id",bid()).order("name");if(r.error)throw r.error;return r.data||[]}
async function getStock(){const r=await db().from("stock_movements").select("id,item_id,quantity,movement_type,reference_type,reference_id,notes,created_at").eq("business_id",bid()).order("created_at",{ascending:false}).limit(500);if(r.error)throw r.error;return r.data||[]}
const stockFor=(item,moves)=>Number(item.opening_stock||0)+moves.filter(m=>m.item_id===item.id&&m.movement_type!=="opening").reduce((a,m)=>a+Number(m.quantity||0),0);
function itemModal(item,refresh){const x=modal(item?"Edit item":"Add item",`<form class="wb-form ob-inv-form" id="ob-item-form">${field("Item name *","name","text",`required value="${esc(item?.name||"")}" placeholder="Product or service"`)}${field("SKU","sku","text",`value="${esc(item?.sku||"")}" placeholder="Optional SKU / code"`)}${field("Category","category","text",`value="${esc(item?.category||"")}" placeholder="e.g. Electronics"`)}<div class="wb-field"><label>Type</label><select name="item_type"><option value="product" ${item?.item_type!=="service"?"selected":""}>Product</option><option value="service" ${item?.item_type==="service"?"selected":""}>Service</option></select></div>${field("Unit","unit","text",`required value="${esc(item?.unit||"pcs")}" placeholder="pcs, kg, box…"`)}${field("Selling price","selling_price","number",`min=0 step=0.01 value="${Number(item?.selling_price||0)}"`)}${field("Purchase price","purchase_price","number",`min=0 step=0.01 value="${Number(item?.purchase_price||0)}"`)}${field("Tax %","tax_rate","number",`min=0 max=100 step=0.01 value="${Number(item?.tax_rate||0)}"`)}${field(item?"Reorder level":"Opening stock","${item?"reorder_level":"opening_stock"}","number",`min=0 step=0.001 value="${Number(item?.[item?"reorder_level":"opening_stock"]||0)}"`)}${item?field("Status","is_active","text",`value="${item.is_active!==false?"Active":"Inactive"}" disabled`):""}<div class="wb-form-actions"><button type="button" class="wb-btn" data-close>Cancel</button><button class="wb-btn primary">${item?"Save changes":"Add item"}</button></div></form>`);x.querySelector("form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),name=String(f.get("name")||"").trim();if(!name){toast("Item name is required");return}const payload={business_id:bid(),name,sku:String(f.get("sku")||"").trim()||null,category:String(f.get("category")||"").trim()||null,item_type:String(f.get("item_type")||"product"),unit:String(f.get("unit")||"pcs").trim()||"pcs",selling_price:Number(f.get("selling_price")||0),purchase_price:Number(f.get("purchase_price")||0),tax_rate:Number(f.get("tax_rate")||0),reorder_level:item?Number(f.get("reorder_level")||0):null};if(!item)payload.opening_stock=Number(f.get("opening_stock")||0);const r=item?await db().from("items").update(payload).eq("id",item.id).eq("business_id",bid()):await db().from("items").insert(payload);if(r.error){toast(r.error.message);return}x.remove();toast(item?"Item updated successfully":"Item added successfully");await refresh()}};
function stockModal(item,current,refresh){const x=modal("Adjust stock",`<form class="wb-form ob-inv-form" id="ob-stock-form"><div class="ob-stock-context"><strong>${esc(item.name)}</strong><span>Current stock: ${qty(current)} ${esc(item.unit||"pcs")}</span></div><div class="wb-field"><label>Movement</label><select name="movement"><option value="purchase">Stock in</option><option value="sale">Stock out</option><option value="adjustment">Adjustment</option><option value="return_in">Customer return</option><option value="return_out">Return to supplier</option></select></div>${field("Quantity *","quantity","number","required min=0.001 step=0.001 placeholder="0")}${field("Note","notes","text","placeholder="Reason or reference")}${field("Reference","reference","text","placeholder="Purchase / return / count reference") }<div class="wb-form-actions"><button type="button" class="wb-btn" data-close>Cancel</button><button class="wb-btn primary">Save movement</button></div></form>`);x.querySelector("form").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),n=Number(f.get("quantity")||0),type=String(f.get("movement")||"adjustment");if(n<=0){toast("Enter a valid quantity");return}let signed=n;if(["sale","return_out"].includes(type))signed=-n;if(type==="adjustment"){const target=current+n;signed=n;}
if(current+signed<0){toast("Stock cannot go below zero");return}const r=await db().from("stock_movements").insert({business_id:bid(),item_id:item.id,quantity:signed,movement_type:type,reference_type:"manual",notes:String(f.get("notes")||"").trim()||null,reference_id:null});if(r.error){toast(r.error.message);return}x.remove();toast("Stock updated successfully");await refresh()}};
async function itemsPage(){const [items,moves]=await Promise.all([getItems(),getStock()]);const panel=document.querySelector("#workspace-content .wb-panel");if(!panel)return;const rows=items.map(i=>({...i,current:stockFor(i,moves)}));const low=rows.filter(i=>i.item_type==="product"&&i.reorder_level!=null&&i.current<=Number(i.reorder_level)).length;panel.dataset.obInventory="items";panel.innerHTML=`<div class="wb-panel-head"><div><h2>Items</h2><p>${items.length} catalogue item${items.length===1?"":"s"}${low?` · <span class="ob-low-head">${low} low stock</span>`:""}</p></div><div class="ob-head-actions"><button class="wb-btn" data-ob="refresh">Refresh</button><button class="wb-btn primary" data-ob="new-item">＋ Add item</button></div></div>${items.length?`<div class="wb-table-wrap"><table class="wb-table ob-inv-table"><thead><tr><th>Item</th><th>SKU</th><th>Type</th><th>Sale price</th><th>Tax</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${rows.map(i=>{const isLow=i.item_type==="product"&&i.reorder_level!=null&&i.current<=Number(i.reorder_level);return `<tr><td><strong>${esc(i.name)}</strong><small class="ob-sub">${esc(i.category||i.unit||"")}</small></td><td>${esc(i.sku||"—")}</td><td>${esc(i.item_type||"product")}</td><td>${money(i.selling_price)}</td><td>${Number(i.tax_rate||0)}%</td><td><strong class="${isLow?"ob-low":""}">${qty(i.current)}</strong> ${esc(i.unit||"pcs")}${isLow?'<span class="ob-low-badge">Low</span>':''}</td><td><div class="ob-row-actions"><button data-ob="stock" data-id="${i.id}">Stock</button><button data-ob="edit" data-id="${i.id}">Edit</button><button data-ob="delete" data-id="${i.id}" class="danger">Delete</button></div></td></tr>`}).join("")}</tbody></table></div>`:`<div class="wb-empty"><div class="wb-empty-icon">◈</div><h3>No items yet</h3><p>Add products or services to start inventory and invoicing.</p><button class="wb-btn primary ob-empty-btn" data-ob="new-item">＋ Add your first item</button></div>`}`;
panel.querySelector('[data-ob="new-item"]').onclick=()=>itemModal(null,itemsPage);panel.querySelector('[data-ob="refresh"]').onclick=itemsPage;panel.querySelectorAll('[data-ob="edit"]').forEach(b=>b.onclick=()=>itemModal(items.find(i=>i.id===b.dataset.id),itemsPage));panel.querySelectorAll('[data-ob="stock"]').forEach(b=>{const i=items.find(i=>i.id===b.dataset.id);b.onclick=()=>stockModal(i,stockFor(i,moves),itemsPage)});panel.querySelectorAll('[data-ob="delete"]').forEach(b=>b.onclick=async()=>{const i=items.find(x=>x.id===b.dataset.id);if(!i)return;if(!confirm(`Delete ${i.name}? This cannot be undone.`))return;const r=await db().from("items").delete().eq("id",i.id).eq("business_id",bid());if(r.error){toast(r.error.message);return}toast("Item deleted");await itemsPage()});}
async function stockPage(){const [items,moves]=await Promise.all([getItems(),getStock()]);const map=Object.fromEntries(items.map(i=>[i.id,i]));const panel=document.querySelector("#workspace-content .wb-panel");if(!panel)return;panel.dataset.obInventory="stock";panel.innerHTML=`<div class="wb-panel-head"><div><h2>Stock</h2><p>Live inventory movements</p></div><button class="wb-btn" data-ob="refresh">Refresh</button></div>${moves.length?`<div class="wb-table-wrap"><table class="wb-table ob-inv-table"><thead><tr><th>Date</th><th>Item</th><th>Movement</th><th>Quantity</th><th>Note</th></tr></thead><tbody>${moves.map(m=>`<tr><td>${new Date(m.created_at).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"})}</td><td><strong>${esc(map[m.item_id]?.name||"Deleted item")}</strong></td><td><span class="ob-movement ${Number(m.quantity)>=0?"in":"out"}">${esc(m.movement_type)}</span></td><td class="${Number(m.quantity)>=0?"ob-in":"ob-out"}">${Number(m.quantity)>=0?"+":""}${qty(m.quantity)} ${esc(map[m.item_id]?.unit||"")}</td><td>${esc(m.notes||"—")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="wb-empty"><div class="wb-empty-icon">◈</div><h3>No stock movements yet</h3><p>Add an item, then record stock coming in or going out.</p></div>`}`;panel.querySelector('[data-ob="refresh"]').onclick=stockPage}
async function enhance(){if(!bid())return;const content=document.querySelector("#workspace-content"),panel=content?.querySelector(".wb-panel");if(!panel)return;const h=content.querySelector("h2")?.textContent?.trim().toLowerCase();try{if(h==="items"&&panel.dataset.obInventory!=="items")await itemsPage();if(h==="stock"&&panel.dataset.obInventory!=="stock")await stockPage()}catch(e){console.error("Orbit inventory",e);toast(e.message||"Inventory failed")}}
let t=0;const obs=new MutationObserver(()=>{clearTimeout(t);t=setTimeout(enhance,140)});obs.observe(document.getElementById("app")||document.body,{childList:true,subtree:true});window.addEventListener("orbitbiz:auth-ready",()=>setTimeout(enhance,200));window.addEventListener("auth:ready",()=>setTimeout(enhance,200));setTimeout(enhance,700);
window.OrbitBiz=window.OrbitBiz||{};window.OrbitBiz.inventoryUX={refresh:itemsPage};
})();