/* Orbit Biz — public landing page */
(() => {
  "use strict";
  const root = document.querySelector("#app");
  if (!root) return;
  const landing = () => `
    <div class="ob-landing" id="orbit-biz-landing"><div class="ob-landing-inner">
      <header class="ob-nav"><button class="ob-brand ob-brand-button" data-ob-action="top"><span class="ob-brand-mark">O</span><span>Orbit</span><small>Biz</small></button><nav class="ob-nav-actions"><button class="ob-link" data-ob-action="features">Features</button><button class="ob-link" data-ob-action="product">Product</button><button class="ob-link" data-ob-action="how">How it works</button><button class="ob-btn ob-btn-light" data-ob-action="signin">Sign in</button><button class="ob-btn ob-btn-dark" data-ob-action="start">Get started</button></nav></header>
      <section class="ob-hero" id="ob-top"><div class="ob-eyebrow"><span class="ob-dot"></span> Business operations, simplified</div><h1>Run your business from <span>one place.</span></h1><p>Sales, customers, invoices, expenses, inventory, payments and reports — connected in one clear workspace built for growing businesses.</p><div class="ob-hero-actions"><button class="ob-btn ob-btn-dark" data-ob-action="start">Start managing your business&nbsp; →</button><button class="ob-btn ob-btn-light" data-ob-action="product">See the product&nbsp; ↓</button></div><div class="ob-note">Built for growing businesses · Designed by Orbit East</div>
        <div class="ob-product" id="ob-product-preview"><div class="ob-browser"><i></i><i></i><i></i><span class="ob-browser-line"></span><span class="ob-browser-url">app.orbitbiz</span></div><div class="ob-dashboard"><aside class="ob-side"><div class="ob-side-logo"><span class="ob-side-mark">O</span> Orbit Biz</div><div class="ob-side-item active">▦ &nbsp; Dashboard</div><div class="ob-side-item">◎ &nbsp; Sales & CRM</div><div class="ob-side-item">▤ &nbsp; Invoices</div><div class="ob-side-item">□ &nbsp; Customers</div><div class="ob-side-item">◈ &nbsp; Inventory</div><div class="ob-side-item">◌ &nbsp; Expenses</div><div class="ob-side-item">⌁ &nbsp; Reports</div></aside><div class="ob-preview-main"><div class="ob-preview-head"><div><span class="ob-preview-kicker">OVERVIEW</span><b>Dashboard</b></div><span class="ob-mini-btn">+ Create new</span></div><div class="ob-stats"><div class="ob-stat"><small>Total sales</small><strong>₹2,84,500</strong><em class="positive">↑ 12.4%</em></div><div class="ob-stat"><small>Receivables</small><strong>₹48,200</strong><em>8 invoices</em></div><div class="ob-stat"><small>Expenses</small><strong>₹96,400</strong><em>This month</em></div><div class="ob-stat"><small>Stock value</small><strong>₹3,42,800</strong><em>126 items</em></div></div><div class="ob-preview-grid"><div class="ob-card"><div class="ob-card-title"><b>Sales overview</b><span>Last 30 days</span></div><div class="ob-chart"><svg viewBox="0 0 600 100" preserveAspectRatio="none"><path d="M0 78 C55 65 75 72 120 58 S205 62 250 43 S335 58 380 31 S470 45 520 22 S570 28 600 10" fill="none" stroke="currentColor" stroke-width="3"/></svg></div></div><div class="ob-card"><div class="ob-card-title"><b>Recent activity</b><span>Today</span></div><div class="ob-list-row">Invoice #1048 <span>₹12,400</span></div><div class="ob-list-row">Payment received <span>₹8,900</span></div><div class="ob-list-row">New customer <span>Today</span></div><div class="ob-list-row">Stock updated <span>12 items</span></div></div></div></div></div></div>
      </section>
      <section class="ob-strip"><div class="ob-strip-inner"><span><strong>Sales</strong> & CRM</span><span><strong>Invoices</strong> & payments</span><span><strong>Inventory</strong> control</span><span><strong>Reports</strong> & insights</span><span><strong>Business</strong> workspace</span></div></section>
      <section class="ob-features" id="ob-features"><div class="ob-section-head"><div class="ob-section-label">ONE WORKSPACE</div><h2>Everything your business needs.</h2><p>Less switching between tools. Less manual work. One workspace that keeps your business information connected.</p></div><div class="ob-feature-grid"><article class="ob-feature"><div class="ob-feature-icon">₹</div><h3>Sales & invoices</h3><p>Create quotations, invoices and receipts while keeping payments and customer balances organised.</p><span class="ob-feature-tag">Sell & collect</span></article><article class="ob-feature"><div class="ob-feature-icon">□</div><h3>Inventory</h3><p>Know what you have, what moved and what needs attention without maintaining separate spreadsheets.</p><span class="ob-feature-tag">Track stock</span></article><article class="ob-feature"><div class="ob-feature-icon">◎</div><h3>Customers & vendors</h3><p>Keep customer and supplier information connected to the transactions that matter.</p><span class="ob-feature-tag">Stay organised</span></article><article class="ob-feature"><div class="ob-feature-icon">↗</div><h3>Reports & insights</h3><p>Turn everyday activity into a clearer picture of sales, expenses and performance.</p><span class="ob-feature-tag">Understand better</span></article><article class="ob-feature"><div class="ob-feature-icon">⌁</div><h3>Payments & accounts</h3><p>Track payment accounts and outstanding amounts so your cash position is easier to understand.</p><span class="ob-feature-tag">Know your cash</span></article><article class="ob-feature"><div class="ob-feature-icon">✓</div><h3>Staff & permissions</h3><p>Give your team the access they need while keeping business operations structured and accountable.</p><span class="ob-feature-tag">Work together</span></article></div></section>
      <section class="ob-problem" id="ob-problem"><div class="ob-problem-copy"><div class="ob-section-label">WHY ORBIT BIZ</div><h2>Your business shouldn't live in five different places.</h2><p>Spreadsheets for stock. Notes for khata. Separate apps for invoices. Messages for customer details. Orbit Biz brings the important pieces together.</p></div><div class="ob-compare"><div class="ob-compare-column ob-before"><span class="ob-compare-label">WITHOUT ORBIT BIZ</span><div>× Bills scattered across apps</div><div>× Stock maintained manually</div><div>× Customer balances hard to follow</div><div>× Business performance unclear</div></div><div class="ob-compare-arrow">→</div><div class="ob-compare-column ob-after"><span class="ob-compare-label">WITH ORBIT BIZ</span><div>✓ One connected workspace</div><div>✓ Inventory stays organised</div><div>✓ Customers & payments stay linked</div><div>✓ Reports show the bigger picture</div></div></div></section>
      <section class="ob-showcase"><div class="ob-showcase-copy"><div class="ob-section-label">BUILT FOR THE DAY-TO-DAY</div><h2>From the first sale to the bigger picture.</h2><p>Orbit Biz is designed around how businesses actually operate — record what happens, keep everything connected, and make better decisions from the data.</p><div class="ob-checks"><span>✓ One business workspace</span><span>✓ Connected operations</span><span>✓ Clear business visibility</span></div></div><div class="ob-flow-card"><div class="ob-flow-step"><b>01</b><div><strong>Record</strong><span>Sales, purchases, expenses & payments</span></div></div><div class="ob-flow-step"><b>02</b><div><strong>Connect</strong><span>Customers, stock, accounts & invoices</span></div></div><div class="ob-flow-step"><b>03</b><div><strong>Understand</strong><span>Reports that turn activity into insight</span></div></div></div></section>
      <section class="ob-how" id="ob-how"><div class="ob-section-head"><div class="ob-section-label">HOW IT WORKS</div><h2>Simple to start. Ready to grow.</h2><p>Get your workspace ready, run your everyday operations, then use the information to move your business forward.</p></div><div class="ob-steps"><article><span>01</span><h3>Set up your business</h3><p>Add your business details, products, customers and the essentials you need to get moving.</p></article><article><span>02</span><h3>Run your day-to-day</h3><p>Create invoices, record sales, manage stock, track expenses and keep payments organised.</p></article><article><span>03</span><h3>Understand your business</h3><p>See what is happening across sales, expenses, receivables, inventory and performance.</p></article></div></section>
      <section class="ob-trust"><div class="ob-trust-copy"><div class="ob-section-label">TRUST & CONTROL</div><h2>Your business data deserves care.</h2><p>Orbit Biz is being built with a structured, business-first foundation — so your data, access and activity can stay organised as your team grows.</p></div><div class="ob-trust-grid"><div><strong>Secure access</strong><span>Authentication designed for real business accounts.</span></div><div><strong>Business isolation</strong><span>Your workspace stays separated from other businesses.</span></div><div><strong>Role-based access</strong><span>Control what team members can see and do.</span></div><div><strong>Activity history</strong><span>Keep important operational actions accountable.</span></div></div></section>
      <section class="ob-usecases"><div class="ob-section-head"><div class="ob-section-label">MADE FOR REAL BUSINESSES</div><h2>Start small. Think bigger.</h2><p>Whether you're running a shop, café, service business or growing operation, Orbit Biz gives you a structured place to run it.</p></div><div class="ob-usecase-grid"><div><span>01</span><strong>Retail</strong><small>Sales, stock, customers & payments</small></div><div><span>02</span><strong>Cafés & restaurants</strong><small>Everyday sales, expenses & inventory</small></div><div><span>03</span><strong>Wholesale</strong><small>Customers, vendors & receivables</small></div><div><span>04</span><strong>Service businesses</strong><small>Customers, invoices & payments</small></div></div></section>
      <section class="ob-growth"><div class="ob-growth-inner"><div><div class="ob-section-label">BUILT TO GROW</div><h2>Start with the essentials.<br><span>Grow into more.</span></h2><p>Orbit Biz is designed as a foundation for a broader business operating system — without forcing you to learn everything on day one.</p></div><div class="ob-future"><span>NOW</span><div>Sales · Invoices · Inventory · Customers · Expenses · Payments · Reports</div><span>NEXT</span><div>Accounting · Purchasing · Analytics · Multi-location · More business tools</div></div></div></section>
      <section class="ob-faq" id="ob-faq"><div class="ob-section-head"><div class="ob-section-label">FAQ</div><h2>Questions, answered.</h2></div><div class="ob-faq-list"><details><summary>What is Orbit Biz?<span>+</span></summary><p>Orbit Biz is business operating software that brings everyday business activities such as sales, invoices, customers, inventory, expenses, payments and reports into one workspace.</p></details><details><summary>Who is Orbit Biz for?<span>+</span></summary><p>It is being designed for small and growing businesses that want a clearer, more connected way to manage day-to-day operations.</p></details><details><summary>Can multiple staff members use it?<span>+</span></summary><p>Yes. The product architecture includes business workspaces, roles and permissions so teams can work together with controlled access.</p></details><details><summary>Is my business data secure?<span>+</span></summary><p>Security is a core part of the architecture, including authenticated access, business-level data isolation and permission controls. Production authentication and deployment safeguards will continue to evolve with the product.</p></details><details><summary>Can I use Orbit Biz from a phone?<span>+</span></summary><p>The interface is designed to be responsive, so the workspace can adapt across desktop and mobile screens.</p></details></div></section>
      <section class="ob-cta"><div class="ob-cta-box"><div class="ob-cta-orbit">O</div><div class="ob-section-label">READY WHEN YOU ARE</div><h2>Your business. One workspace.</h2><p>Start with the essentials and build from there. Orbit Biz is designed to keep everyday operations simple and connected.</p><div class="ob-cta-actions"><button class="ob-btn ob-btn-light" data-ob-action="start">Get started with Orbit Biz&nbsp; →</button><button class="ob-cta-text" data-ob-action="signin">Already have an account? Sign in</button></div></div></section>
      <footer class="ob-footer"><span>© 2026 <strong>Orbit East</strong></span><span>Orbit Biz · Business operating software</span><div><button data-ob-action="features">Features</button><button data-ob-action="faq">FAQ</button></div></footer>
    </div></div>`;
  root.insertAdjacentHTML("afterbegin", landing());
  const page = document.querySelector("#orbit-biz-landing");
  const scrollTo = id => document.querySelector(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  page.addEventListener("click", event => { const button = event.target.closest("[data-ob-action]"); if (!button) return; const action = button.dataset.obAction; if (action === "top") scrollTo("#ob-top"); if (action === "features") scrollTo("#ob-features"); if (action === "product") scrollTo("#ob-product-preview"); if (action === "how") scrollTo("#ob-how"); if (action === "faq") scrollTo("#ob-faq"); if (action === "signin" || action === "start") { const mode = action === "signin" ? "signin" : "signup"; window.dispatchEvent(new CustomEvent("orbitbiz:auth-request", { detail: { mode } })); if (window.OrbitBiz?.events?.emit) window.OrbitBiz.events.emit("auth:request", { mode }); } });
})();
