/* OrbitBiz — public landing page */
(() => {
  "use strict";
  const root = document.querySelector("#app");
  if (!root) return;
  const landing = () => `
    <div class="ob-landing" id="orbit-biz-landing"><div class="ob-landing-inner">
      <header class="ob-nav">
        <button class="ob-brand ob-brand-button" data-ob-action="top" aria-label="OrbitBiz home"><img class="ob-brand-mark" src="assets/orbiteastfavicon.png" alt="OrbitBiz"><span>Orbit</span><small>Biz</small></button>
        <nav class="ob-nav-actions" aria-label="Main navigation"><button class="ob-link" data-ob-action="apps">Apps</button><button class="ob-link" data-ob-action="features">Features</button><button class="ob-link" data-ob-action="how">How it works</button><button class="ob-link" data-ob-action="pricing">Pricing</button><button class="ob-btn ob-btn-light" data-ob-action="signin">Sign in</button><button class="ob-btn ob-btn-dark" data-ob-action="start">Start now</button></nav>
      </header>
      <section class="ob-hero" id="ob-top"><div class="ob-eyebrow"><span class="ob-dot"></span> One workspace for your business</div><h1>Everything your business needs.<br><span>All in one place.</span></h1><p>Run sales, CRM, invoicing, inventory, purchasing, expenses, payments and reporting from one connected business workspace.</p><div class="ob-hero-actions"><button class="ob-btn ob-btn-dark" data-ob-action="start">Start using OrbitBiz&nbsp; →</button><button class="ob-btn ob-btn-light" data-ob-action="product">Explore the workspace&nbsp; ↓</button></div><div class="ob-note">No complicated setup · Built for growing businesses</div>
        <div class="ob-product" id="ob-product-preview"><div class="ob-browser"><i></i><i></i><i></i><span class="ob-browser-line"></span><span class="ob-browser-url">app.orbitbiz</span></div><div class="ob-dashboard"><aside class="ob-side"><div class="ob-side-logo"><img class="ob-side-mark" src="assets/orbiteastfavicon.png" alt=""> OrbitBiz</div><div class="ob-side-item active">▦ &nbsp; Dashboard</div><div class="ob-side-item">◎ &nbsp; CRM</div><div class="ob-side-item">₹ &nbsp; Sales</div><div class="ob-side-item">▤ &nbsp; Invoices</div><div class="ob-side-item">□ &nbsp; Customers</div><div class="ob-side-item">◈ &nbsp; Inventory</div><div class="ob-side-item">⌁ &nbsp; Reports</div></aside><div class="ob-preview-main"><div class="ob-preview-head"><div><span class="ob-preview-kicker">BUSINESS OVERVIEW</span><b>Good morning</b></div><span class="ob-mini-btn">+ Create</span></div><div class="ob-stats"><div class="ob-stat"><small>Sales this month</small><strong>₹2,84,500</strong><em class="positive">↑ 12.4%</em></div><div class="ob-stat"><small>Receivables</small><strong>₹48,200</strong><em>8 outstanding</em></div><div class="ob-stat"><small>Expenses</small><strong>₹96,400</strong><em>This month</em></div><div class="ob-stat"><small>Inventory value</small><strong>₹3,42,800</strong><em>126 items</em></div></div><div class="ob-preview-grid"><div class="ob-card"><div class="ob-card-title"><b>Sales performance</b><span>Last 30 days</span></div><div class="ob-chart"><svg viewBox="0 0 600 100" preserveAspectRatio="none"><path d="M0 78 C55 65 75 72 120 58 S205 62 250 43 S335 58 380 31 S470 45 520 22 S570 28 600 10" fill="none" stroke="currentColor" stroke-width="3"/></svg></div></div><div class="ob-card"><div class="ob-card-title"><b>Recent activity</b><span>Today</span></div><div class="ob-list-row">Invoice #1048 <span>₹12,400</span></div><div class="ob-list-row">Payment received <span>₹8,900</span></div><div class="ob-list-row">New customer <span>Today</span></div><div class="ob-list-row">Stock updated <span>12 items</span></div></div></div></div></div></div>
      </section>
      <section class="ob-strip" id="ob-apps"><div class="ob-strip-inner"><span><strong>CRM</strong> & customers</span><span><strong>Sales</strong> & invoices</span><span><strong>Inventory</strong> & purchasing</span><span><strong>Expenses</strong> & payments</span><span><strong>Reports</strong> & insights</span></div></section>
      <section class="ob-features" id="ob-features"><div class="ob-section-head"><div class="ob-section-label">YOUR BUSINESS, CONNECTED</div><h2>One need. One workspace.</h2><p>Keep the core of your business together instead of moving between disconnected tools.</p></div><div class="ob-feature-grid"><article class="ob-feature"><div class="ob-feature-icon">◎</div><h3>CRM</h3><p>Track leads, customers, opportunities and conversations in one place.</p><span class="ob-feature-tag">Build relationships</span></article><article class="ob-feature"><div class="ob-feature-icon">₹</div><h3>Sales & invoicing</h3><p>Move from quotation to invoice and payment without re-entering the same information.</p><span class="ob-feature-tag">Sell faster</span></article><article class="ob-feature"><div class="ob-feature-icon">◈</div><h3>Inventory</h3><p>Track products, stock levels, warehouses and movements with a clear operational view.</p><span class="ob-feature-tag">Control stock</span></article><article class="ob-feature"><div class="ob-feature-icon">▣</div><h3>Purchasing</h3><p>Manage suppliers, purchase orders, receipts and vendor payments from the same system.</p><span class="ob-feature-tag">Buy smarter</span></article><article class="ob-feature"><div class="ob-feature-icon">⌁</div><h3>Finance</h3><p>Keep expenses, payment accounts, receivables and financial activity connected.</p><span class="ob-feature-tag">Know your numbers</span></article><article class="ob-feature"><div class="ob-feature-icon">↗</div><h3>Reports</h3><p>Turn daily business activity into useful information for better decisions.</p><span class="ob-feature-tag">See the bigger picture</span></article></div></section>
      <section class="ob-problem" id="ob-how"><div class="ob-problem-copy"><div class="ob-section-label">DESIGNED FOR PRODUCTIVITY</div><h2>Less data entry.<br>More work done.</h2><p>When a customer, product or transaction is created once, the information can move through the rest of your workflow instead of being entered again and again.</p></div><div class="ob-compare"><div class="ob-compare-column ob-before"><span class="ob-compare-label">OLD WAY</span><div>× Separate spreadsheets</div><div>× Repeated data entry</div><div>× Scattered customer records</div><div>× Manual stock tracking</div></div><div class="ob-compare-arrow">→</div><div class="ob-compare-column ob-after"><span class="ob-compare-label">ORBITBIZ</span><div>✓ Connected business records</div><div>✓ Reusable customer & product data</div><div>✓ Sales linked to payments</div><div>✓ Inventory stays up to date</div></div></div></section>
      <section class="ob-showcase"><div class="ob-showcase-copy"><div class="ob-section-label">CONNECTED OPERATIONS</div><h2>From first contact to payment.</h2><p>OrbitBiz is built around complete business flows. Create information once, connect it to the next step and keep the history available when you need it.</p><div class="ob-checks"><span>✓ Customer → quotation → sale</span><span>✓ Sale → invoice → payment</span><span>✓ Purchase → receipt → stock</span><span>✓ Activity → reports → decisions</span></div></div><div class="ob-flow-card"><div class="ob-flow-step"><b>01</b><div><strong>Connect</strong><span>Customers, products and business records</span></div></div><div class="ob-flow-step"><b>02</b><div><strong>Operate</strong><span>Sales, purchases, inventory and payments</span></div></div><div class="ob-flow-step"><b>03</b><div><strong>Understand</strong><span>Reports and business performance</span></div></div></div></section>
      <section class="ob-how"><div class="ob-section-head"><div class="ob-section-label">GET STARTED</div><h2>Simple from day one.</h2><p>Start with what you need today. Expand your workspace as your business grows.</p></div><div class="ob-steps"><article><span>01</span><h3>Create your workspace</h3><p>Add your business information and set up the essentials.</p></article><article><span>02</span><h3>Run your business</h3><p>Manage customers, sales, inventory, expenses and payments from one place.</p></article><article><span>03</span><h3>Grow with insight</h3><p>Use connected records and reports to understand what is happening.</p></article></div></section>
      <section class="ob-trust"><div class="ob-trust-copy"><div class="ob-section-label">CONTROL & SECURITY</div><h2>Your data. Your business.</h2><p>Business software should keep your information organised and under your control, with access designed around the people who actually use the system.</p></div><div class="ob-trust-grid"><div><strong>Secure authentication</strong><span>Protected access for business accounts.</span></div><div><strong>Business isolation</strong><span>Business data stays separated by workspace.</span></div><div><strong>Role-based access</strong><span>Give team members the right level of access.</span></div><div><strong>Connected history</strong><span>Keep important activity tied to the right records.</span></div></div></section>
      <section class="ob-usecases"><div class="ob-section-head"><div class="ob-section-label">FOR EVERYDAY BUSINESS</div><h2>Built to fit how you work.</h2><p>Use one foundation whether you sell products, provide services or manage a growing operation.</p></div><div class="ob-usecase-grid"><div><span>01</span><strong>Retail</strong><small>Sales · stock · customers · payments</small></div><div><span>02</span><strong>Services</strong><small>Customers · invoices · expenses</small></div><div><span>03</span><strong>Wholesale</strong><small>Products · vendors · receivables</small></div><div><span>04</span><strong>Growing teams</strong><small>Roles · reports · operations</small></div></div></section>
      <section class="ob-growth" id="ob-pricing"><div class="ob-growth-inner"><div><div class="ob-section-label">A BUSINESS PLATFORM</div><h2>Start with the essentials.<br><span>Build as you grow.</span></h2><p>OrbitBiz is being developed as a broader business operating system, so the foundation you use today can support more workflows tomorrow.</p></div><div class="ob-future"><span>AVAILABLE</span><div>CRM · Sales · Invoices · Inventory · Customers · Expenses · Payments · Reports</div><span>EXPANDING</span><div>Accounting · Purchasing · Analytics · Multi-location · More business tools</div></div></div></section>
      <section class="ob-faq" id="ob-faq"><div class="ob-section-head"><div class="ob-section-label">FAQ</div><h2>Questions, answered.</h2></div><div class="ob-faq-list"><details><summary>What is OrbitBiz?<span>+</span></summary><p>OrbitBiz is a connected business management workspace for sales, CRM, invoicing, inventory, purchasing, expenses, payments and reporting.</p></details><details><summary>Who is it for?<span>+</span></summary><p>OrbitBiz is designed for small and growing businesses that want their everyday operations in one clear system.</p></details><details><summary>Can my team use it?<span>+</span></summary><p>Yes. The product is designed around business workspaces, authentication, roles and permissions.</p></details><details><summary>Can I use it on mobile?<span>+</span></summary><p>The interface is responsive and designed to adapt across desktop, tablet and mobile screens.</p></details></div></section>
      <section class="ob-cta"><div class="ob-cta-box"><div class="ob-cta-orbit">O</div><div class="ob-section-label">READY TO GET STARTED?</div><h2>Run your business in one place.</h2><p>Bring your customers, sales, stock, payments and business information together with OrbitBiz.</p><div class="ob-cta-actions"><button class="ob-btn ob-btn-light" data-ob-action="start">Start with OrbitBiz&nbsp; →</button><button class="ob-cta-text" data-ob-action="signin">Already have an account? Sign in</button></div></div></section>
      <footer class="ob-footer"><span>© 2026 <strong>Orbit East</strong></span><span>OrbitBiz · Business management platform</span><div><button data-ob-action="apps">Apps</button><button data-ob-action="faq">FAQ</button></div></footer>
    </div></div>`;
  root.insertAdjacentHTML("afterbegin", landing());
  const page = document.querySelector("#orbit-biz-landing");
  if (!page) return;
  const scrollTo = id => document.querySelector(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  page.addEventListener("click", event => {
    const button = event.target.closest("[data-ob-action]");
    if (!button) return;
    const action = button.dataset.obAction;
    if (action === "top") scrollTo("#ob-top");
    if (action === "apps") scrollTo("#ob-apps");
    if (action === "features") scrollTo("#ob-features");
    if (action === "product") scrollTo("#ob-product-preview");
    if (action === "how") scrollTo("#ob-how");
    if (action === "pricing") scrollTo("#ob-pricing");
    if (action === "faq") scrollTo("#ob-faq");
    if (action === "signin" || action === "start") {
      const mode = action === "signin" ? "signin" : "signup";
      window.dispatchEvent(new CustomEvent("orbitbiz:auth-request", { detail: { mode } }));
      if (window.OrbitBiz?.events?.emit) window.OrbitBiz.events.emit("auth:request", { mode });
    }
  });
})();
