/* OrbitBiz unified workspace controls: list, kanban, search, filters, grouping, favourites and bulk actions. */
(()=>{ "use strict";
const state={route:"",view:"list",query:"",group:null,filter:"all"};
const titles={dashboard:"Dashboard",invoices:"Sales",clients:"Contacts",crm:"CRM",quotations:"Quotations",proforma:"Proforma",receipts:"Receipts",items:"Products",stock:"Inventory",warehouses:"Warehouses",purchases:"Purchase",["purchase-orders"]:"Purchase Orders",["vendor-payments"]:"Vendor Payments",expenses:"Expenses",["payment-accounts"]:"Accounts",reports:"Reporting",gst:"GST",["accounting-reports"]:"Accounting",reconciliation:"Reconciliation",settings:"Settings"};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const root=()=>document.querySelector(".workspace-content")||document.querySelector(".workspace-main")||document.getElementById("app");const route=()=>document.querySelector(".workspace-nav-item.active")?.dataset.page||"dashboard";const tables=()=>[...root()?.querySelectorAll("table")||[]];const key=r=>`orbitbiz.view.${r}`;
function openAction(r){const el=document.querySelector(r==="invoices"?'[data-action="new-invoice"],[data-action="create-invoice"]':'[data-action="quick-add"]');if(el){el.click();return}document.dispatchEvent(new CustomEvent("orbit:quick-add",{detail:{page:r}}))}
function saved(r){try{return JSON.parse(localStorage.getItem(key(r))||"null")}catch{return null}}function persist(r){try{localStorage.setItem(key(r),JSON.stringify({view:state.view,filter:state.filter,group:state.group}))}catch{}}
function addToolbar(r){const host=root();if(!host)return;let bar=host.querySelector(":scope > .orbit-odoo-toolbar");if(!bar){bar=document.createElement("div");bar.className="orbit-odoo-toolbar";host.prepend(bar)}let favs=[];try{favs=JSON.parse(localStorage.getItem("orbitbiz.favourites")||"[]")}catch{}
bar.innerHTML=`<div class="orbit-control-title"><span>${esc(titles[r]||r)}</span><button class="orbit-fav ${favs.includes(`${r}:${state.query}:${state.filter}:${state.group||""}`)?"active":""}" data-fav>★</button></div><button class="primary" data-new>New</button><div class="orbit-search-wrap"><span>⌕</span><input class="orbit-odoo-search" data-search value="${esc(state.query)}" placeholder="Search ${esc(titles[r]||r)}…"></div><div class="orbit-control-menu"><button data-menu="filter">Filters ⌄</button><div class="orbit-dropdown" data-drop="filter"><button data-filter="all">All records</button><button data-filter="active">Active</button><button data-filter="recent">Recently updated</button><button data-filter="empty">No value</button></div></div><div class="orbit-control-menu"><button data-menu="group">Group By ⌄</button><div class="orbit-dropdown" data-drop="group"><button data-group="none">No grouping</button>${groupOptions()}</div></div><div class="orbit-viewset"><button data-view="list" class="${state.view==="list"?"active":""}">☷</button><button data-view="kanban" class="${state.view==="kanban"?"active":""}">▦</button></div>`;
bar.querySelector('[data-new]')?.addEventListener('click',()=>openAction(r));bar.querySelector('[data-search]')?.addEventListener('input',e=>{state.query=e.target.value;apply()});bar.querySelectorAll('[data-menu]').forEach(b=>b.onclick=e=>{e.stopPropagation();bar.querySelector(`[data-drop="${b.dataset.menu}"]`)?.classList.toggle('open')});bar.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;persist(r);apply();closeMenus()});bar.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{state.group=b.dataset.group==='none'?null:b.dataset.group;persist(r);apply();closeMenus()});bar.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;persist(r);renderView()});bar.querySelector('[data-fav]')?.addEventListener('click',()=>{const k=`${r}:${state.query}:${state.filter}:${state.group||""}`;let a=[];try{a=JSON.parse(localStorage.getItem('orbitbiz.favourites')||'[]')}catch{};a=a.includes(k)?a.filter(x=>x!==k):[...a,k];localStorage.setItem('orbitbiz.favourites',JSON.stringify(a));addToolbar(r)})}
function groupOptions(){const t=tables()[0],h=[...(t?.tHead?.rows?.[0]?.cells||[])].map((c,i)=>({i,text:c.textContent.trim()})).filter(x=>x.text&&x.i<8);return h.map(x=>`<button data-group="${x.i}">${esc(x.text)}</button>`).join('')}
function closeMenus(){document.querySelectorAll('.orbit-dropdown.open').forEach(x=>x.classList.remove('open'))}
function apply(){rows().forEach(({tr})=>{const txt=tr.textContent.toLowerCase();let ok=!state.query||txt.includes(state.query.toLowerCase());if(state.filter==='active')ok=ok&&!/inactive|archived|cancelled/i.test(txt);if(state.filter==='empty')ok=ok&&[...tr.cells].some(c=>!c.textContent.trim());tr.hidden=!ok});renderGroups();syncSelection()}
function rows(){return tables().flatMap(t=>[...(t.tBodies?.[0]?.rows||[])].map(tr=>({tr,table:t})).filter(x=>!x.tr.classList.contains('orbit-group-row')))}
function renderGroups(){document.querySelectorAll('.orbit-group-row').forEach(x=>x.remove());if(state.view!=='list'||state.group==null)return;tables().forEach(t=>{const body=t.tBodies?.[0];if(!body)return;const all=[...body.rows].filter(r=>!r.hidden&&!r.classList.contains('orbit-group-row'));const idx=Number(state.group);const map=new Map();all.forEach(r=>{const k=(r.cells[idx]?.textContent||'Other').trim()||'Other';if(!map.has(k))map.set(k,[]);map.get(k).push(r)});body.innerHTML='';map.forEach((list,k)=>{const g=document.createElement('tr');g.className='orbit-group-row';g.innerHTML=`<td colspan="${t.tHead?.rows?.[0]?.cells.length||1}"><strong>${esc(k)}</strong><span>${list.length}</span></td>`;body.appendChild(g);list.forEach(r=>body.appendChild(r))})})}
function renderView(){tables().forEach(t=>t.classList.toggle('orbit-kanban-mode',state.view==='kanban'));if(state.view==='list')renderGroups();else document.querySelectorAll('.orbit-group-row').forEach(x=>x.remove())}
function syncSelection(){const host=root();if(!host)return;let b=host.querySelector(':scope > .orbit-selection-bar');if(!b){b=document.createElement('div');b.className='orbit-selection-bar';b.innerHTML='<strong data-selected-count>0 selected</strong><button data-clear>Clear</button><button data-export>Export</button>';host.prepend(b);b.querySelector('[data-clear]').onclick=()=>{host.querySelectorAll('.orbit-row-check').forEach(x=>x.checked=false);syncSelection()};b.querySelector('[data-export]').onclick=exportSelected}const n=host.querySelectorAll('tbody .orbit-row-check:checked').length;b.classList.toggle('show',n>0);b.querySelector('[data-selected-count]').textContent=`${n} selected`}
function selection(){tables().forEach(t=>{if(t.dataset.orbitSelect)return;t.dataset.orbitSelect='1';const h=t.tHead?.rows?.[0];if(!h)return;const th=document.createElement('th');th.innerHTML='<input type="checkbox" class="orbit-row-check orbit-all-check">';h.prepend(th);[...t.tBodies?.[0]?.rows||[]].forEach(r=>{const td=document.createElement('td');td.innerHTML='<input type="checkbox" class="orbit-row-check">';r.prepend(td)});t.addEventListener('change',e=>{if(!e.target.classList.contains('orbit-row-check'))return;if(e.target.classList.contains('orbit-all-check'))t.querySelectorAll('tbody .orbit-row-check').forEach(x=>x.checked=e.target.checked);syncSelection()})})}
function exportSelected(){const lines=[];tables().forEach(t=>{const h=[...t.tHead.rows[0].cells].map(c=>c.textContent.trim());[...t.tBodies[0].rows].filter(r=>r.querySelector('.orbit-row-check:checked')).forEach(r=>lines.push(h.map((_,i)=>JSON.stringify(r.cells[i]?.textContent.trim()||'')).join(',')))});const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));a.download=`orbitbiz-${state.route}-export.csv`;a.click()}
function enhance(){const r=route(),host=root();if(!host)return;if(state.route!==r){state.route=r;const s=saved(r);state.view=s?.view||'list';state.filter=s?.filter||'all';state.group=s?.group??null;state.query='';host.querySelector(':scope > .orbit-odoo-toolbar')?.remove();host.querySelector(':scope > .orbit-selection-bar')?.remove()}addToolbar(r);selection();apply();renderView()}
let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(enhance,150)};new MutationObserver(schedule).observe(document.getElementById('app')||document.body,{subtree:true,childList:true});document.addEventListener('orbit:workspace-ready',schedule);document.addEventListener('click',e=>{if(!e.target.closest('.orbit-control-menu'))closeMenus()});window.addEventListener('load',schedule);schedule();
})();
