/* OrbitBiz connected kanban board */
(()=>{
'use strict';
const cfg=()=>window.OrbitBiz?.config||{};
const db=()=>window.OrbitBiz?.auth?.getClient?.()||window.supabase?.createClient?.(cfg().supabaseUrl,cfg().supabaseKey);
const bid=()=>localStorage.getItem('orbitbiz.activeBusinessId')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const routes={crm:{table:'crm',title:'Leads',name:'name',stages:['new','qualified','proposition','won','lost'],amount:'expected_value'},quotations:{table:'quotations',title:'Quotations',name:'quote_number',stages:['draft','sent','accepted','rejected'],amount:'total'},proforma:{table:'proforma_invoices',title:'Proforma',name:'proforma_number',stages:['draft','sent','accepted','cancelled'],amount:'total'},invoices:{table:'invoices',title:'Sales',name:'invoice_number',stages:['draft','posted','paid','cancelled'],amount:'total'},purchases:{table:'purchases',title:'Purchase',name:'purchase_number',stages:['draft','received','paid','cancelled'],amount:'total'},'purchase-orders':{table:'purchase_orders',title:'Purchase Orders',name:'po_number',stages:['draft','sent','confirmed','received','cancelled'],amount:'total'},expenses:{table:'expenses',title:'Expenses',name:'description',stages:['draft','posted'],amount:'amount'}};
let active=null;
const toast=m=>window.toast?window.toast(m):console.info(m);
async function load(meta){const r=await db().from(meta.table).select('*').eq('business_id',bid()).order('created_at',{ascending:false}).limit(300);if(r.error)throw r.error;return r.data||[]}
function currentStatus(row,meta){return String(row.status||meta.stages[0]).toLowerCase()}
function money(v){const n=Number(v);return Number.isFinite(n)&&n!==0?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n):''}
function render(rows,meta){const host=document.querySelector('#workspace-content');if(!host)return;host.querySelector('.orbit-kanban-board')?.remove();const board=document.createElement('div');board.className='orbit-kanban-board';board.innerHTML=meta.stages.map(stage=>`<section class="orbit-kanban-column" data-stage="${esc(stage)}"><header><div><strong>${esc(stage.replace(/[-_]/g,' '))}</strong><span class="orbit-kanban-count">0</span></div><button data-stage-new="${esc(stage)}" title="Create record">＋</button></header><div class="orbit-kanban-cards" data-drop-stage="${esc(stage)}"></div></section>`).join('');host.appendChild(board);
const groups=new Map(meta.stages.map(s=>[s,[]]));rows.forEach(r=>{const s=currentStatus(r,meta);(groups.get(s)||groups.get(meta.stages[0])).push(r)});
groups.forEach((list,stage)=>{const col=board.querySelector(`[data-stage="${CSS.escape(stage)}"]`);if(!col)return;col.querySelector('.orbit-kanban-count').textContent=list.length;const wrap=col.querySelector('.orbit-kanban-cards');list.forEach(row=>{const card=document.createElement('article');card.className='orbit-kanban-card';card.draggable=true;card.dataset.id=row.id;card.dataset.stage=stage;card.innerHTML=`<div class="orbit-card-top"><strong>${esc(row[meta.name]||'Untitled')}</strong><span>⋮</span></div><div class="orbit-card-meta">${esc(row.customer_name||row.company_name||row.category||row.phone||'')}</div>${meta.amount?`<div class="orbit-card-amount">${money(row[meta.amount])}</div>`:''}<div class="orbit-card-footer"><span>${esc((row.updated_at||row.created_at||'').slice(0,10))}</span><button data-open-record="${esc(row.id)}">Open</button></div>`;wrap.appendChild(card);card.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',JSON.stringify({id:row.id,from:stage}));card.classList.add('dragging')});card.addEventListener('dragend',()=>card.classList.remove('dragging'));card.querySelector('[data-open-record]').onclick=()=>{document.dispatchEvent(new CustomEvent('orbit:open-record',{detail:{route:active,id:row.id,record:row}}))}})});
board.querySelectorAll('[data-drop-stage]').forEach(drop=>{drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-over')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag-over'));drop.addEventListener('drop',async e=>{e.preventDefault();drop.classList.remove('drag-over');let d;try{d=JSON.parse(e.dataTransfer.getData('text/plain'))}catch{return}const to=drop.dataset.dropStage;if(!d?.id||d.from===to)return;try{const r=await db().from(meta.table).update({status:to}).eq('id',d.id).eq('business_id',bid());if(r.error)throw r.error;toast(`Moved to ${to.replace(/[-_]/g,' ')}`);render(await load(meta),meta)}catch(err){toast(err.message||'Could not move record')}})});
board.querySelectorAll('[data-stage-new]').forEach(b=>b.onclick=()=>{document.dispatchEvent(new CustomEvent('orbit:quick-add',{detail:{page:active,status:b.dataset.stageNew}}))});
}
async function enhance(){const r=document.querySelector('.workspace-nav-item.active')?.dataset?.page;const meta=routes[r];if(!meta)return;if(active===r&&document.querySelector('.orbit-kanban-board'))return;active=r;try{render(await load(meta),meta)}catch(e){toast('Kanban could not load records')}}
document.addEventListener('orbit:kanban-request',enhance);document.addEventListener('click',e=>{const b=e.target.closest('[data-view="kanban"]');if(b){setTimeout(enhance,80)}});document.addEventListener('orbit:workspace-ready',()=>setTimeout(()=>{if(active)enhance()},100));
window.OrbitBizKanban={open:enhance};
})();